### PR TITLE
Renew worker creds on time, even after hibernation

### LINKED ISSUE #5269: worker-runner credential renewal does not work if the system goes to sleep
After having a windows multi-user worker running idle for a while, credentials expired and were not refreshed by start-worker meaning it was stuck and not accepting tasks anymore. start-worker should refresh those credentials and restart the worker I guess.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #5269

See the issue -- I'm not sure this is worth fixing?

### CODE REVIEW

File: tools/worker-runner/util/nonmonotonic_test.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+func TestSleepUntilWallClockTime(t *testing.T) {
+	until := time.Now().Add(time.Millisecond * 10)
+	require.True(t, SleepUntilWallClock(until, context.Background()))
+	require.GreaterOrEqual(t, time.Now().UnixMilli(), until.UnixMilli())
+}
+
+func TestSleepUntilWallClockTimeCancel(t *testing.T) {
+	until := time.Now().Add(time.Second * 10)
+	ctx, _ := context.WithTimeout(context.Background(), 10*time.Millisecond)
```
Comment (petemoore) [inline tools/worker-runner/util/nonmonotonic_test.go:19]:
```
Running golangci-lint..
tools/worker-runner/util/nonmonotonic_test.go:19:7: lostcancel: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (govet)
	ctx, _ := context.WithTimeout(context.Background(), 10*time.Millisecond)
	     ^
error Command failed with exit code 1.
```

**Review by petemoore — CHANGES_REQUESTED** [review]

File: tools/worker-runner/util/nonmonotonic_test.go (hunk 1 above)
Comment (djmitche) [reply tools/worker-runner/util/nonmonotonic_test.go:19]: I really wish govet didn't run on tests, but ok :)

**Review by matt-boris — APPROVED** [review]
