### PR TITLE
Queue API validation rules

### LINKED ISSUE #7757: "Output schema validation errors"
Sentry reports some "Output schema validation errors" like this:

```
schema: "https://community-tc.services.mozilla.com/schemas/queue/https://community-tc.services.mozilla.com/schemas/queue/v1/pending-tasks-response.json#"
stack: "Error: Output schema validation error: 
Schema Validation Failed!
Rejecting Schema: https://community-tc.services.mozilla.com/schemas/queue/v1/pending-tasks-response.json#
Errors:
  * data/workerType must match pattern "^[a-z]([-a-z0-9]{0,36}[a-z0-9])?$"
  * data/taskQueueId must match pattern "^[a-zA-Z0-9-_]{1,38}/[a-z]([-a-z0-9]{0,36}[a-z0-9])?$"
    at res.reply (file:///app/libraries/api/src/middleware/schema.js:90:23)
    at Proxy.<anonymous> (file:///app/services/queue/src/api.js:2014:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"
url: "/pending/1%2F1"
v: 1
```

Queue API endpoints should validate incoming parameters before it is being validated on the output.

### PR DESCRIPTION
**Pull request by lotas**
There was a slight mismatch between output schema validation and input validation, which resulted in 500 errors instead of 400

 Fixes #7757

### CODE REVIEW

**Review by matt-boris — APPROVED** [review]

File: services/queue/src/api.js [hunk 1]
```diff
@@ -57,9 +57,10 @@ const PRIORITY_LEVELS = [
  */
 
 // Common patterns URL parameters
-let SLUGID_PATTERN = /^[A-Za-z0-9_-]{8}[Q-T][A-Za-z0-9_-][CGKOSWaeimquy26-][A-Za-z0-9_-]{10}[AQgw]$/;
-let GENERIC_ID_PATTERN = /^[a-zA-Z0-9-_]{1,38}$/;
-let RUN_ID_PATTERN = /^[1-9]*[0-9]+$/;
+const SLUGID_PATTERN = /^[A-Za-z0-9_-]{8}[Q-T][A-Za-z0-9_-][CGKOSWaeimquy26-][A-Za-z0-9_-]{10}[AQgw]$/;
+const GENERIC_ID_PATTERN = /^[a-zA-Z0-9-_]{1,38}$/;
+const RUN_ID_PATTERN = /^[1-9]*[0-9]+$/;
+const TASK_QUEUE_ID_PATTERN = new RegExp('^[a-zA-Z0-9-_]{1,38}/[a-z]([-a-z0-9]{0,36}[a-z0-9])?$');
```
Comment (petemoore) [inline services/queue/src/api.js:63]: is there a constant already exported somewhere for worker pool id pattern and worker type pattern, that TASK_QUEUE_ID_PATTERN could be composed of (so the regexp's aren't duplicated across multiple sites)?

Comment (lotas) [reply services/queue/src/api.js:63]: Good question! I haven't seen regexp concatenation so far. 
And only exists in the constants.yml of the schemas at the moment

Comment (lotas) [reply services/queue/src/api.js:63]: I think this can be placed into a separate or existing shared library. Maybe https://github.com/taskcluster/taskcluster/blob/bba5a9367bfa895e26b6937a23c48569d9ef2de7/libraries/references/README.md?plain=1#L1   references library is a good place to put all regexes and import in services from that single place?
