### PR TITLE
Provide a link to the build artifacts in taskcluster community web pages. 

### LINKED ISSUE #1949: Provide a link to the build artifacts in taskcluster community web pages.
**Describe the bug**

The the previous version of taskcluster, it was possible to get a link to a page listing the build artifacts. However, after being moved to community taskcluster, the new web pages no longer provide a way to get a direct link to the build artifacts. I now have to provide a link to the task run page and provide instructions to click the little arrow to show the artifacts.

**To Reproduce**

1. Go to 'https://community-tc.services.mozilla.com/tasks/QW3amtG3SkK3Tp5lBSq_tg'

**Expected behavior**

There should be a way to either link to the build artifacts or the UI state should be saved in the URL so that when the artifact arrow is toggled the link reflects that. 
**Screenshots**

Screenshot_2019-11-11 Firefox Reality For Android Build Master Update - Community-TC

**Platform (please complete the following information):**

 - OS: [e.g. windows] Probably not relevant but both linux and mac.
 - Browser if applicable [e.g. firefox, safari] Firefox
 - Version if applicable [e.g. 57] All

### PR DESCRIPTION
**Pull request by km-js**
Fixes #1949

### CODE REVIEW

File: ui/src/components/TaskRunsCard/index.jsx [hunk 1]
```diff
@@ -183,6 +183,13 @@ export default class TaskRunsCard extends Component {
   };
 
   handleToggleArtifacts = () => {
+    const { history } = this.props;
+    const { taskId } = this.getCurrentRun();
+    const { showArtifacts } = this.state;
+
+    !showArtifacts
+      ? history.replace(`/tasks/${taskId}#artifacts`)
+      : history.replace(`/tasks/${taskId}`);
```
Comment (helfi92) [inline ui/src/components/TaskRunsCard/index.jsx]: If a user navigates to https://community-tc.services.mozilla.com/tasks/QW3amtG3SkK3Tp5lBSq_tg#artifacts, will this have the artifacts panel open on page load?

Comment (km-js) [reply ui/src/components/TaskRunsCard/index.jsx]: No, how should we deal with that?

Comment (helfi92) [reply ui/src/components/TaskRunsCard/index.jsx]: You can do this by having `showArtifacts` linked to the hash instead of state.

Instead of 

```
const { showArtifacts } = this.state;
```

We could probably just do:

```
const showArtifacts = window.location.hash === '#artifacts';
```

File: ui/src/components/TaskRunsCard/index.jsx [hunk 2]
```diff
@@ -283,6 +291,7 @@ export default class TaskRunsCard extends Component {
     const { showArtifacts, showMore } = this.state;
     const run = this.getCurrentRun();
     const liveLogArtifact = this.getLiveLogArtifactFromRun(run);
+    const hashInUrl = window.location.hash === '#artifacts';
```
Comment (helfi92) [inline ui/src/components/TaskRunsCard/index.jsx]: `const showArtifacts = window.location.hash === '#artifacts';` then you can remove `showArtifacts` from `state`.

Comment (km-js) [reply ui/src/components/TaskRunsCard/index.jsx]: Sure👍
