### PR TITLE
[Bug 1518568] Turn on more lint rules

### LINKED ISSUE #46: Add no-unused-vars
Is there any specific reason why  we have left out `no-unused-vars` ?

### PR DESCRIPTION
**Pull request by imbstack**
This is one step of enabling the remaining useful rules in eslint. There are other rules remaining. A couple of actual bugs turned up in here I think.

Most were harmless. Some of the removals below were scripted. eslint does not provide a `--fix` for this option. You might have an easier time reading through this commit by commit although most of them are large anyway.

Fixes #46 

Bugzilla Bug: [1518568](https://bugzilla.mozilla.org/show_bug.cgi?id=1518568)

### CODE REVIEW

File: services/queue/test/artifact_test.js [hunk 1]
```diff
@@ -364,9 +362,9 @@ helper.secrets.mockSuite(__filename, ['taskcluster', 'aws', 'azure'], function(m
       // Probably overkill because the schema should catch this but not the
       // worst idea
       for (let i of [0, 1, 2]) {
-        assume(response.requests[0]).to.have.property('url');
-        assume(response.requests[1]).to.have.property('method');
-        assume(response.requests[2]).to.have.property('headers');
+        assume(response.requests[i]).to.have.property('url');
+        assume(response.requests[i]).to.have.property('method');
+        assume(response.requests[i]).to.have.property('headers');
```
Comment (djmitche) [inline services/queue/test/artifact_test.js]: whoops!

**Comment by imbstack** [comment]
Thanks to you both! I have fixed the merge conflicts and will land this before it gets further out of date. I'll deploy all of our services and watch them after this. I figure any issues this causes will show up quickly so Friday shouldn't be too big of an issue.

**Comment by imbstack** [comment]
Oops, didn't mean to merge quite yet. Oh well. I'll watch and fix anything that fails from this.
