### PR TITLE
feat(w-m): Fix azure stuck worker removal

### LINKED ISSUE #8086: ARM Deployment issue - workers stuck in "stopping" state
Happened in this worker pool https://community-tc.services.mozilla.com/worker-manager/proj-taskcluster%2Fgw-windows-2022-staging/errors 

After arm deployment failed, worker was not created, but worker scanner is stuck in some internal loop - cannot fully stop/remove worker.

Original provision error was:

```json
     "code": "PublicIPCountLimitReached",
          "details": [],
          "message": "Cannot create more than 10 public IP addresses for this subscription in this region."
        }
```

<details>
<summary>Worker's providerData sample contents</summary>

```json
{
  "ip": {
    "id": "/sub..mstla-ip",
    "name": "vm-qbw08z5riojxdvihwgc6aupa0misztmstla-ip"
  },
  "vm": {
    "id": false,
    "name": "nonexistent",
    "vmId": false,
    "customData": "ey....Q==",
    "computerName": "ubqd5ckptrask4c"
  },
  "nic": { "id": false, "name": "nonexistent" },
  "tags": {
    "owner": "taskcluster-notifications+workers@mozilla.com",
    "root-url": "https://community-tc.services.mozilla.com",
    "created-by": "taskcluster-wm-community-tc-workers-azure",
    "managed-by": "taskcluster",
    "provider-id": "community-tc-workers-azure",
    "worker-group": "centralus",
    "worker-pool-id": "proj-taskcluster/gw-windows-2022-staging",
    "launch-config-id": "lc-2ab208c0e0f1033247cd"
  },
  "disks": [],
  "location": "centralus",
  "deployment": {
    "id": false,
    "name": "deploy-qbw08z5riojxdvihwgc6aupa0misztmstla"
  },
  "workerConfig": {
    "genericWorker": {
      ...
    }
  },
  "armDeployment": {
    "mode": "Incremental",
    "parameters": {
      "vmSize": { "value": "Standard_F16s_v2" },
      "imageId": {
        "value": "/subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-images/providers/Microsoft.Compute/images/imageset-vxutupixiwvrtxqdqkpa-centralus"
      },
      "location": { "value": "centralus" },
      "subnetId": {
        "value": "/subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/rg-tc-eng-vnets/providers/Microsoft.Network/virtualNetworks/tc-vnet-centralus/subnets/default"
      }
    },
    "templateLink": {
      "id": "/subscriptions/8a205152-b25a-417f-a676-80465535a6c9/resourceGroups/templates-rg/providers/Microsoft.Resources/templateSpecs/arm-tpl-test-1/versions/3.0"
    }
  },
  "reasonRemoved": "deployment Failed: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "workerManager": {
    "stoppedAt": "2025-11-14T03:29:05.359Z",
    "previousState": "requested"
  },
  "keepDeployment": false,
  "terminateAfter": 1763436474261,
  "deploymentMethod": "arm-template",
  "resourceGroupName": "rg-tc-eng-worker-manager-VMs",
  "reregistrationTimeout": 345600000,
  "queueInactivityTimeout": 7200000
}

```
</details>

### PR DESCRIPTION
**Pull request by lotas**
When ARM deployment failed validation step - no deployment was ever created, but checkARMDeployment was kept running forever without marking deployment as complete (in sense that nothing more is happening)

Fixes #8086

### CODE REVIEW

File: services/worker-manager/src/providers/azure/index.js [hunk 1]
```diff
@@ -1489,6 +1484,11 @@ export class AzureProvider extends Provider {
       }
     }
 
+    if (worker.state === states.STOPPING) {
```
Comment (lotas) [inline services/worker-manager/src/providers/azure/index.js:1487]: restored this block to it's original state - shorting the circuit if the worker is stopping, and moved the arm deployment check above this, so that at this point we no longer care how it was provisioned
