### PR TITLE
generic-worker, d2g: let containers talk to the tc proxy without sharing the host network namespace

### LINKED ISSUE #6797: d2g: --net=host causes problems for android pgo kvm jobs
**Describe the bug**
runtask is failing at https://searchfox.org/mozilla-central/rev/961556b584938a694d7df6e7bf25d70253c37060/taskcluster/scripts/run-task#797 under Generic Worker.

See broken [treeherder job](https://treeherder.mozilla.org/logviewer?job_id=444475711&repo=try&lineNumber=246). Broken [taskcluster task](https://firefox-ci-tc.services.mozilla.com/tasks/T7ds8_QTTFaeVRCXN3msNw/runs/0/logs/public/logs/live.log#L246).

Under docker worker, this works. See working docker worker [treeherder job](https://treeherder.mozilla.org/jobs?repo=try&revision=7fd3a844e044bb8af7cdacd16ebfe4598e079e64&selectedTaskRun=dUtz5PcyTBWqwTwG59XgJg.0). Working [taskcluster task](https://firefox-ci-tc.services.mozilla.com/tasks/dUtz5PcyTBWqwTwG59XgJg) or maybe [this one](https://treeherder.mozilla.org/jobs?repo=try&revision=fe50bb952ccf4ae6db913684aa00a5bd49ee02a0&selectedTaskRun=XXdjmREoSUS9cHpxpUTnLQ.0) (need to double check).

@jrmuizel says:

> the Xvfb problem looks like it’s caused by the abstract unix domain socket namespace being shared with container because of -net=host. See https://stackoverflow.com/questions/74733639/cannot-bind-x-unix-socket-within-docker-container

The reason we chose `--net=host` rather than e.g. `--net=private` was to keep things simple. Tasks _should_ use `$TASKCLUSTER_PROXY_URL` for accessing the taskcluster proxy (which we could change inside the podman container) _but_ they may also be explicitly using e.g. explicit references to expected proxy location with commands like `curl -fsSL http://localhost:80/api/queue/v1/task/...`, and we [would like these to keep working](https://linuxreviews.org/WE_DO_NOT_BREAK_USERSPACE) too under Generic Worker. So we ideally need to find a way to have taskcluster proxy urls work regardless of whether they are hardcoded with `http://localhost` or whether they use `$TASKCLUSTER_PROXY_URL` but at the same time, we need the kvm stuff to work too that is broken as described above.

### LINKED ISSUE #7320: d2g: don't use `--net=host`
d2g uses `--net=host` if a task wants access to the taskcluster proxy.  That gives the task privileged access to the host, which it shouldn't have.

### PR DESCRIPTION
**Pull request by jcristau**
Github Bug/Issue: Fixes #7320, fixes #6797

### CODE REVIEW

File: tools/d2g/d2g.go [hunk 1]
```diff
@@ -568,10 +568,6 @@ func envMappings(dwPayload *dockerworker.DockerWorkerPayload) string {
 		"TASK_ID",
 	}
 
-	if dwPayload.Features.TaskclusterProxy {
-		additionalEnvVars = append(additionalEnvVars, "TASKCLUSTER_PROXY_URL")
-	}
-
```
Comment (matt-boris) [inline tools/d2g/d2g.go:574]: I think I would prefer having any and all env vars be added directly in this helper `envMappings()` function. So this could change to something like:
```go
if dwPayload.Features.TaskclusterProxy {
    additionalEnvVars = append(additionalEnvVars, "TASKCLUSTER_PROXY_URL=${TASKCLUSTER_PROXY_URL}/localhost/taskcluster")
}
```

File: tools/d2g/d2g.go [hunk 2]
```diff
@@ -357,10 +357,10 @@ func runCommand(containerName string, dwPayload *dockerworker.DockerWorkerPayloa
 		command.WriteString(" --security-opt=seccomp=unconfined")
 	}
 	command.WriteString(createVolumeMountsString(dwPayload, wdcs))
+	command.WriteString(envMappings(dwPayload))
```
Comment (matt-boris) [inline tools/d2g/d2g.go:360]: Any reason for the different ordering?

File: tools/d2g/d2g.go [hunk 3]
```diff
@@ -357,10 +357,10 @@ func runCommand(containerName string, dwPayload *dockerworker.DockerWorkerPayloa
...
 	if dwPayload.Features.TaskclusterProxy {
-		command.WriteString(" --add-host=taskcluster:127.0.0.1 --net=host")
+		command.WriteString(" --add-host=taskcluster:host-gateway -e TASKCLUSTER_PROXY_URL=${TASKCLUSTER_PROXY_URL/localhost/taskcluster}")
```
Comment (matt-boris) [inline tools/d2g/d2g.go:362]: I'm not familiar with adding this `host-gateway`. Do you have any tasks you made manually that uses this that the container has access to the tc proxy?

**Review by matt-boris — COMMENTED** [review]
Thanks for helping look into this!

File: tools/d2g/d2g.go (hunk 1 above)
Comment (jcristau) [reply tools/d2g/d2g.go:574]: That doesn't work, because additionalEnvVars is then passed through `shell.Escape` (via `envSetting`).

Comment (jcristau) [reply tools/d2g/d2g.go:574]: Also, the `/localhost/taskcluster` does need to be within the braces.

File: tools/d2g/d2g.go (hunk 2 above)
Comment (jcristau) [reply tools/d2g/d2g.go:360]: No particular reason.

File: tools/d2g/d2g.go (hunk 3 above)
Comment (jcristau) [reply tools/d2g/d2g.go:362]: That would need a g-w with the first patch here, for the proxy to listen on the docker interface.

Per https://docs.docker.com/reference/cli/docker/container/run/#add-host "The `--add-host` flag supports a special `host-gateway` value that resolves to the internal IP address of the host. This is useful when you want containers to connect to services running on the host machine."

File: tools/d2g/d2g.go (hunk 1 above)
Comment (matt-boris) [reply tools/d2g/d2g.go:574]: Ah right, thanks, I had forgotten about `shell.Escape`.

File: tools/d2g/d2g.go (hunk 2 above)
Comment (jcristau) [reply tools/d2g/d2g.go]: Reordered.

Comment (matt-boris) [reply tools/d2g/d2g.go]: It'll make it so you don't have to reorder so many of the test cases, keep the diff to what's truly changing here 👍🏻

File: tools/d2g/d2g.go (hunk 3 above)
Comment (matt-boris) [reply tools/d2g/d2g.go:361]: Thanks 👍🏻 Are you planning on doing the generic worker/tc proxy patch too? We can assist however you'd like/need.

**Review by matt-boris — COMMENTED** [review]
Changes LGTM, let's just build a staging pool off of this commit and do some testing before merging! 👍🏻

**Comment by matt-boris** [comment]
Building our ubuntu staging image off of https://github.com/taskcluster/taskcluster/tree/d2g-proxy.

**Comment by matt-boris** [comment]
Successful tests with docker https://community-tc.services.mozilla.com/tasks/SZGlDbShTn6DCtsXzTngHA/runs/0
and podman https://community-tc.services.mozilla.com/tasks/BbZ9bsxUTr2QF6gwZT3M1A/runs/0

**Review by matt-boris — APPROVED** [review]
LGTM, will you please rebase with `main` and we'll get this merged?
