### PR TITLE
[UI] Search terms with empty table results 

### LINKED ISSUE #2607: [UI] Search terms with empty table results
**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/secrets
2. Search for something that doesn't exist (e.g., foo-bar-foo)

**Expected behavior**
"No  items for this page with search term foo-bar-foo." is shown.

**Actual behavior**

"No items for this page." is shown. It's hard to infer whether there are no results for this page or no results for this search term.

Screen Shot 2020-04-06 at 8 36 38 AM

**Taskcluster version**
28.0.0

---

Once this is done for the secrets view, we will want to replicate this to all of the other tables we use in the UI.

### PR DESCRIPTION
**Pull request by rohanharikr**
Github Bug/Issue: Fixes #2607

@helfi92 Thanks a ton for the help!

### CODE REVIEW

File: ui/src/components/ConnectionDataTable/index.jsx [hunk 1]
```diff
@@ -256,7 +259,7 @@ export default class ConnectionDataTable extends Component {
               {connection.edges.length === 0 ? (
                 <TableRow>
                   <TableCell colSpan={colSpan}>
-                    <em>No items for this page.</em>
+                    <em>{searchTerm ? `No items for this page with the search term ${searchTerm}.` : noItemsMessage}</em>
```
Comment (helfi92) [inline ui/src/components/ConnectionDataTable/index.jsx:262]: ``` <em>{searchTerm ? `No items for this page with search term ${searchTerm}.` : noItemsMessage}</em> ```

File: ui/src/components/SecretsTable/index.jsx [hunk 2]
```diff
@@ -100,6 +100,7 @@ export default class SecretsTable extends Component {
 
     return (
       <ConnectionDataTable
+        searchTerm  ={searchTerm}
```
Comment (helfi92) [inline ui/src/components/SecretsTable/index.jsx:103]: Remove extra white spaces.

```searchTerm={searchTerm} ```

**Comment by helfi92** [comment]
https://community-tc.services.mozilla.com/tasks/F9TvbunRTn-k4wVvQ0gtDw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FF9TvbunRTn-k4wVvQ0gtDw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

You'll want to run `yarn lint --fix` from within the ui directory and push the changes.

File: ui/src/components/ConnectionDataTable/index.jsx (hunk 1 above)
Comment (helfi92) [reply ui/src/components/ConnectionDataTable/index.jsx]: This still needs to be done. Remove "the" before "search term".

**Comment by rohanharikr** [comment]
@helfi92 Looking into it!

**Comment by helfi92** [comment]
Hm, the last commit would show a table with no message when a table has no search result and no actual content. Maybe we should just leave it like your previous implementation was :) Sorry for that. Let's remove the last commit.

Also, do you want to add the same logic to the other views with tables? We can either do it here or in a separate PR. Happy to help.

**Comment by rohanharikr** [comment]
@helfi92 for now, this was done for just clients page. please allow me a days time to add the changes to all the needed pages.

Also, this page is not facing that issue where we clear the input field, it goes to "No items for this page" and then to full results.

Let me see what is different in this and the secrets page. Once I figure it out, I will be able to fix that bug!

**Comment by rohanharikr** [comment]
@helfi92 Done! Thanks :)
sorry, but was unable to implement this in the /roles

File: ui/src/components/SecretsTable/index.jsx [hunk 3]
```diff
@@ -89,7 +89,7 @@ export default class SecretsTable extends Component {
   }
 
   render() {
-    const { onPageChange, classes, secretsConnection } = this.props;
+    const { onPageChange, classes, secretsConnection, searchTerm } = this.props;
```
Comment (helfi92) [inline ui/src/components/SecretsTable/index.jsx:92]: `searchTerm` should be added to `propTypes` and `defaultProps`. The default value can be null. Same with the other ones.

```jsx
propTypes = {
  searchTerm: string,
};

defaultProps = {
  searchTerm: null,
};
```

File: ui/src/views/Secrets/ViewSecrets/index.jsx [hunk 4]
```diff
@@ -36,21 +36,20 @@ export default class ViewSecrets extends Component {
...
-    refetch({
+    await refetch({
       secretsConnection: {
         limit: VIEW_SECRETS_PAGE_SIZE,
       },
       filter: secretSearch
         ? { name: { $regex: escapeStringRegexp(secretSearch), $options: 'i' } }
         : null,
     });
+    this.setState({ secretSearch });
```
Comment (helfi92) [inline ui/src/views/Secrets/ViewSecrets/index.jsx:52]: 👍

File: ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx [hunk 5]
```diff
@@ -232,7 +233,11 @@ export default class ListNamespaces extends Component {
             </Fragment>
           )}
           {!loading && !hasNamespaces && !hasIndexedTasks && isSinglePath && (
-            <Typography variant="body2">No items for this page.</Typography>
+            <Typography variant="body2">
+              {searchTerm
+                ? `No items for this page with search term ${searchTerm}.`
+                : 'No items for this page.'}
+            </Typography>
```
Comment (helfi92) [inline ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx:240]: I think the reason why we had this hard-coded here was because we didn't support the `searchTerm` prop to the the table. Now that we do, we could probably just feed the search term to the table like the other views. Should we do that here?

File: ui/src/components/RoleScopesTable/index.jsx [hunk 6]
```diff
@@ -139,7 +139,9 @@ export default class RoleScopesTable extends Component {
       </List>
     ) : (
       <Typography variant="body2" className={classes.noRolesText}>
-        No roles available
+        {searchTerm
+          ? `No roles available with search term ${searchTerm}.`
+          : 'No roles available'}
```
Comment (helfi92) [inline ui/src/components/RoleScopesTable/index.jsx:144]: Do you know why it's not working? Btw, you can access this view in http://localhost:5080/auth/scopes. There are two tables there.

**Comment by helfi92** [comment]
There seems to be a conflict, probably because a file on master changed recently. Could you try pulling the recent changes and fixing the code conflict, please?

**Comment by helfi92** [comment]
The conflict most probably came from https://github.com/taskcluster/taskcluster/pull/2651.

File: ui/src/components/RolesTable/index.jsx [hunk 7]
```diff
@@ -30,7 +30,7 @@ export default class RolesTable extends Component {
       pageInfo,
     }).isRequired,
     onPageChange: func.isRequired,
-    /** A search term to refine the list of roles */
+    /** Value of search field */
```
Comment (helfi92) [inline ui/src/components/RolesTable/index.jsx:33]: Was this changed by mistake?

File: ui/src/components/SecretsTable/index.jsx [hunk 8]
```diff
@@ -27,7 +27,13 @@ const sorted = pipe(
  * Display secrets in a table.
  */
 export default class SecretsTable extends Component {
+  static defaultProps = {
+    searchTerm: null,
+  };
+
   static propTypes = {
+    /** A search term to refine the list of roles */
```
Comment (helfi92) [inline ui/src/components/SecretsTable/index.jsx:35]: `s/roles/secrets/`

File: ui/src/components/WMWorkerPoolsTable/index.jsx [hunk 9]
```diff
@@ -58,6 +58,10 @@ export default class WorkerManagerWorkerPoolsTable extends Component {
     deleteRequest: func.isRequired,
   };
 
+  static defaultProps = {
```
Comment (helfi92) [inline ui/src/components/WMWorkerPoolsTable/index.jsx:61]: `searchTerm` is missing in `propTypes`.

File: ui/src/components/RolesTable/index.jsx (hunk 7 above)
Comment (helfi92) [reply ui/src/components/RolesTable/index.jsx:33]: Also, let's add a comment if possible for all places we are adding `searchTerm` in propTypes.

File: ui/src/components/SecretsTable/index.jsx [hunk 10]
```diff
@@ -27,7 +27,13 @@ const sorted = pipe(
  * Display secrets in a table.
  */
 export default class SecretsTable extends Component {
+  static defaultProps = {
```
Comment (helfi92) [inline ui/src/components/SecretsTable/index.jsx:30]: Default props without knowing the actual props can be confusing. Not too important, but if we can have `propTypes` come before `defaultProps`, it would be great :)

File: ui/src/views/Clients/ViewClients/index.jsx [hunk 11]
```diff
@@ -138,6 +147,7 @@ export default class ViewClients extends PureComponent {
           <ErrorPanel fixed error={error} />
           {clients && (
             <ClientsTable
+              searchTerm={this.props.history.location.search.slice(8)}
```
Comment (helfi92) [inline ui/src/views/Clients/ViewClients/index.jsx:150]: `.slice(8)`?

File: ui/src/views/Clients/ViewClients/index.jsx [hunk 12]
```diff
@@ -121,6 +126,7 @@ export default class ViewClients extends PureComponent {
       description,
       data: { loading, error, clients },
     } = this.props;
+    const { search } = this.state;
```
Comment (helfi92) [inline ui/src/views/Clients/ViewClients/index.jsx:129]: No need to have internal state. We can get this value from the URL. Here's an example where it is done:

https://github.com/taskcluster/taskcluster/blob/d7753390faf752a84b2370f905d07d34257f41d0/ui/src/views/Hooks/ListHooks/index.jsx#L53-L54

Comment (helfi92) [reply ui/src/views/Clients/ViewClients/index.jsx:129]: While you're at it, if you feed the value of the search term to the `defaultValue`, then the search term will show in the search box on page reload.

```jsx
<Search
  // ...
  defaultValue={searchTerm}
/>
```

File: ui/src/views/Roles/ViewRoles/Roles.jsx [hunk 13]
```diff
@@ -30,14 +29,6 @@ import { VIEW_ROLES_PAGE_SIZE } from '../../../utils/constants';
   }),
 })
 export default class Roles extends PureComponent {
-  static propTypes = {
-    searchTerm: string,
-  };
-
-  static defaultProps = {
-    searchTerm: null,
-  };
```
Comment (helfi92) [inline ui/src/views/Roles/ViewRoles/Roles.jsx:39]: This function still reads the `searchTerm` prop so we should have it in `propTypes` and `defaultProps`.

File: ui/src/views/Roles/ViewRoles/index.jsx [hunk 14]
```diff
@@ -19,7 +19,7 @@ export default class ViewRoles extends PureComponent {
     roleSearch: '',
   };
 
-  handleRoleSearchSubmit = roleSearch => {
+  handleRoleSearchSubmit = async roleSearch => {
```
Comment (helfi92) [inline ui/src/views/Roles/ViewRoles/index.jsx:22]: There isn't anything that uses `await` in this function. We can remove `async`.

File: ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx (hunk 5 above)
Comment (helfi92) [reply ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx:241]: In the render method of this file, we use either `IndexNamespacesTable` or `IndexTaskNamespaceTable` to render the table. Are we able to provide the search term to those functions and let the table handle providing this message rather than hard-coding it here?

File: ui/src/views/WorkerManager/WMViewWorkerPools/index.jsx [hunk 15]
```diff
@@ -146,6 +147,7 @@ export default class WorkerManagerWorkerPoolsView extends Component {
           {WorkerManagerWorkerPoolSummaries && (
             <Fragment>
               <WorkerManagerWorkerPoolsTable
+                searchTerm={workerPoolSearch}
```
Comment (helfi92) [inline ui/src/views/WorkerManager/WMViewWorkerPools/index.jsx:150]: Is `WorkerManagerWorkerPoolsTable` making use of this search term?

Comment (rohanharikr) [reply ui/src/views/WorkerManager/WMViewWorkerPools/index.jsx:150]: Yes. `searchTerm` is passed to the `ConnectionDataTable` in `WorkerManagerWorkerPoolsTable` where it is rendered.

File: ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx [hunk 16]
```diff
@@ -234,11 +234,11 @@ export default class ListNamespaces extends Component {
...
-              {searchTerm
-                ? `No items for this page with search term ${searchTerm}.`
-                : noItemsMessage}
-            </Typography>
+            <IndexNamespacesTable
+              searchTerm={searchTerm}
+              connection={taskNamespace}
+              onPageChange={this.handleTaskNamespacePageChange}
+            />
           )}
```
Comment (helfi92) [inline ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx:241]: Ah, sorry for that. Let's just bring it back like it was before.

File: ui/src/views/Clients/ViewClients/index.jsx [hunk 17]
```diff
@@ -121,13 +121,16 @@ export default class ViewClients extends PureComponent {
       description,
       data: { loading, error, clients },
     } = this.props;
+    const searchUri = qs.parse(this.props.history.location.search.slice(1));
```
Comment (helfi92) [inline ui/src/views/Clients/ViewClients/index.jsx:124]: Rename to `searchQuery`.

File: ui/src/components/RoleScopesTable/index.jsx [hunk 18]
```diff
@@ -50,13 +50,16 @@ const sorted = pipe(
 }))
```
Comment (helfi92) [inline ui/src/components/RoleScopesTable/index.jsx:50]: Hm, I see a change to RoleScopesTable but not to ClientScopesTable. Do we need to feed the searchTerm prop to `ConnectionDataTable`?

File: ui/src/views/Clients/ViewClients/index.jsx (hunk 17 above)
Comment (helfi92) [inline ui/src/views/Clients/ViewClients/index.jsx:124]:
```jsx
{
  // ...
  location,
} = this.props;
const searchQuery = qs.parse(location.search.slice(1));
```

File: ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx [hunk 19]
```diff
@@ -174,6 +174,7 @@ export default class ListNamespaces extends Component {
     const loading = namespacesLoading || taskNamespaceLoading;
     const indexPaths = indexPathInput.split('.');
     const isSinglePath = indexPaths.length === 1;
+    const searchTerm = this.props.match.params.namespace;
```
Comment (helfi92) [inline ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx:177]:
```jsx
{
 // ...
 match: { params },
} = this.props;
// ...
const searchTerm = params.namespace;
```

**Comment by helfi92** [comment]
@all-contributors please add @rohanharikr for code.

File: ui/src/components/RoleScopesTable/index.jsx (hunk 18 above)
Comment (rohanharikr) [reply ui/src/components/RoleScopesTable/index.jsx:50]: Added this now. Didn't add it at first because this view doesn't return anything regarding the search made.

Screenshot 2020-04-30 at 3 31 27 AM

File: ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx [hunk 20]
```diff
@@ -165,6 +165,7 @@ export default class ListNamespaces extends Component {
         error: taskNamespaceError,
       },
       description,
+      match: { params },
```
Comment (helfi92) [inline ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx:168]: This seems to throw an error for me locally. It turns out it was added on masters 2 days ago:

https://github.com/taskcluster/taskcluster/blob/266ecb3e97b857c324078eaf88a83034b456b232/ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx#L157

Pulling the latest changes on master should fix this.

File: ui/src/views/Clients/ViewClients/index.jsx [hunk 21]
```diff
@@ -119,15 +119,19 @@ export default class ViewClients extends PureComponent {
     const {
       classes,
       description,
+      location,
       data: { loading, error, clients },
     } = this.props;
+    const searchQuery = qs.parse(location.search.slice(1));
```
Comment (helfi92) [inline ui/src/views/Clients/ViewClients/index.jsx:125]: `parse` is already defined on line 4. We could just use it directly and remove  `qs` from both here and line 4.
