### PR TITLE
Bug 1588099 - simplify scope expressions (reland)

### LINKED ISSUE #2318: UI uses tc-lib-scopes, which now requires lodash and json-stable-stringify
https://app.netlify.com/sites/taskcluster-web/deploys/5e3c9c8c64d9e2000ae68341

### PR DESCRIPTION
**Pull request by djmitche**
Bugzilla Bug: [1588099](https://bugzilla.mozilla.org/show_bug.cgi?id=1588099)

Fixes #2318.

### CODE REVIEW

File: infrastructure/tooling/src/smoketest/index.js [hunk 1]
```diff
@@ -21,14 +21,15 @@ const main = async (options) => {
   const res = await auth.currentScopes();
   if (!libScopes.satisfiesExpression(res.scopes, scopeExpression)) {
     const required = libScopes.removeGivenScopes(res.scopes, scopeExpression);
+    console.log(JSON.stringify(scopeExpression, null, 2));
```
Comment (imbstack) [inline infrastructure/tooling/src/smoketest/index.js]: stray?

Comment (djmitche) [reply infrastructure/tooling/src/smoketest/index.js]: indeed, thanks!
