### PR TITLE
fix(d2g): duplicate image with separate IDs get handled properly

### LINKED ISSUE #7969: D2G - issue loading docker image if the image already exists with a different ID
First task that's run on the machine works fine:

```bash
[taskcluster 2025-09-22T13:07:03.317Z] [mounts] Downloading task MB2Em7uFRxWOUxlQgcY1tA artifact public/image.tar.zst to downloads/ddFZsAaGQj6EWo4NQXKHcg
[taskcluster 2025-09-22T13:07:21.101Z] [mounts] Downloaded 803137941 bytes with SHA256 c10fdb0be409aa6f57f607fa9f35513de291856ef0497121b3d4f507e3ddd7b1 from task MB2Em7uFRxWOUxlQgcY1tA artifact public/image.tar.zst to downloads/ddFZsAaGQj6EWo4NQXKHcg
[taskcluster:warn 2025-09-22T13:07:21.101Z] [mounts] Download downloads/ddFZsAaGQj6EWo4NQXKHcg of task MB2Em7uFRxWOUxlQgcY1tA artifact public/image.tar.zst has SHA256 c10fdb0be409aa6f57f607fa9f35513de291856ef0497121b3d4f507e3ddd7b1 but task payload does not declare a required value, so content authenticity cannot be verified
[taskcluster 2025-09-22T13:07:21.101Z] [mounts] Creating directory /home/task_175854642221483
[taskcluster 2025-09-22T13:07:21.121Z] [mounts] Copying downloads/ddFZsAaGQj6EWo4NQXKHcg to /home/task_175854642221483/dockerimage
[taskcluster 2025-09-22T13:07:27.839Z] [mounts] Granting task_175854642221483 full control of file '/home/task_175854642221483/dockerimage'
[taskcluster 2025-09-22T13:07:30.074Z] [d2g] Loading docker image
[taskcluster 2025-09-22T13:08:03.236Z] [d2g] Loaded docker image "toolchain-build:latest"
```

then we get this on subsequent runs:

```bash
[taskcluster 2025-09-22T13:11:15.714Z] [mounts] Downloading task Kgp7RMZDTqS8nzOZNM27eA artifact public/image.tar.zst to downloads/bMfCx62-QsW7BHuAh-qNNw
[taskcluster 2025-09-22T13:11:29.497Z] [mounts] Downloaded 806067280 bytes with SHA256 6127aab0341f08c9bb22013300f199a2e1d8aa6c440ab954acec82e158d225f9 from task Kgp7RMZDTqS8nzOZNM27eA artifact public/image.tar.zst to downloads/bMfCx62-QsW7BHuAh-qNNw
[taskcluster:warn 2025-09-22T13:11:29.497Z] [mounts] Download downloads/bMfCx62-QsW7BHuAh-qNNw of task Kgp7RMZDTqS8nzOZNM27eA artifact public/image.tar.zst has SHA256 6127aab0341f08c9bb22013300f199a2e1d8aa6c440ab954acec82e158d225f9 but task payload does not declare a required value, so content authenticity cannot be verified
[taskcluster 2025-09-22T13:11:29.497Z] [mounts] Creating directory /home/task_175854652872700
[taskcluster 2025-09-22T13:11:29.516Z] [mounts] Copying downloads/bMfCx62-QsW7BHuAh-qNNw to /home/task_175854652872700/dockerimage
[taskcluster 2025-09-22T13:11:36.177Z] [mounts] Granting task_175854652872700 full control of file '/home/task_175854652872700/dockerimage'
[taskcluster 2025-09-22T13:11:38.448Z] [d2g] Loading docker image
[taskcluster 2025-09-22T13:12:11.666Z] [d2g] Loaded docker image "The image toolchain-build:latest already exists, renaming the old one with ID sha256:375d8dc60e145ca9019bd5d629450aae469a1e1c7da9657e383b93d9e2aff3de to empty string"
```

### PR DESCRIPTION
**Pull request by matt-boris**
Fixes #7969.

>D2G: fixes issue with loading the docker image artifact if the image already exists with a separate ID, causing the following output to be improperly parsed by D2G: `The image <imageName> already exists, renaming the old one with ID <sha> to empty string`.

### CODE REVIEW

File: workers/generic-worker/d2g_feature.go [hunk 1]
```diff
@@ -111,12 +111,20 @@ func (dtf *D2GTaskFeature) Start() *CommandExecutionError {
...
 		if isImageArtifact {
-			imageName = strings.TrimPrefix(imageName, "Loaded image: ")
+			// Find the first line with "Loaded image: " prefix
+			// (see https://github.com/taskcluster/taskcluster/issues/7969)
+			for _, line := range lines {
+				if name, found := strings.CutPrefix(line, "Loaded image: "); found {
+					imageName = name
+					break
+				}
+			}
```
Comment (petemoore) [inline workers/generic-worker/d2g_feature.go:130]: should we handle the case the line isn't found?

**Review by petemoore — APPROVED** [review]

File: workers/generic-worker/d2g_feature.go (hunk 1 above)
Comment (matt-boris) [reply workers/generic-worker/d2g_feature.go:130]: Handling now https://github.com/taskcluster/taskcluster/pull/7970/files#diff-acb243059a525ef0410312b05f2a9fc08b4504e2d08a0aac2e880b044c8596a4R132-R134

**Review by petemoore — APPROVED** [review]
Love it, thank you!
