### PR TITLE
fix handling of named parameters to db functions

### LINKED ISSUE #3999: db.fns named parameters only work if given in order
`libraries/postgres/src/Database.js` uses [`yesql`](https://classic.yarnpkg.com/en/package/yesql) to convert named parameters to unnamed parameters before calling postgres with them.  It provides the names of the parameters to `yesql` in the order they were given in the argument to the DB function.

So, given a DB function `foo(a_in string, b_in string, c_in string)`, this will work:

```js
db.fns.foo({
  a_in: 'aardvark',
  b_in: 'bullfrog',
  c_in: 'caterpillar',
});
```
but this will not:
```js
db.fns.foo({
  c_in: 'caterpillar',
  b_in: 'bullfrog',
  a_in: 'aardvark',
});
```

Postgres [supports named arguments directly](https://www.postgresql.org/docs/11/sql-syntax-calling-funcs.html) so we could just use that functionality rather than yesql.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #3999

### CODE REVIEW

File: libraries/postgres/test/database_test.js [hunk 1]
```diff
@@ -94,14 +94,14 @@ helper.dbSuite(path.basename(__filename), function() {
             return 'got ' || x;
           end`,
         },
-        add_from_numbers_named: {
+        sub_from_numbers_named: {
```
Comment (imbstack) [inline libraries/postgres/test/database_test.js:97]: why change this to subtraction?

File: libraries/postgres/src/Database.js [hunk 2]
```diff
@@ -109,9 +108,11 @@ class Database {
           try {
             let res;
             if (hasNamedArguments) {
-              const placeholders = Object.keys(args[0]).map(arg => `:${arg}`).join(',');
-              const { text, values } = named(`select * from "${method.name}"(${placeholders})`, { useNullForMissing: true })(args[0]);
-              res = await client.query(text, values);
+              const obj = args[0];
+              const keys = Object.keys(obj);
+              const values = keys.map(k => obj[k]); // order must match keys!
+              const placeholders = keys.map((key, i) => `${key} => $${i + 1}`).join(',');
```
Comment (imbstack) [inline libraries/postgres/src/Database.js:114]: could you inject something by naming a key in a certain way here?

**Review by imbstack — APPROVED** [review]
I think this makes sense. I wonder what the point of `yesql` even is if it requires order to be maintained?

File: libraries/postgres/test/database_test.js (hunk 1 above)
Comment (djmitche) [reply libraries/postgres/test/database_test.js:97]: Because addition is commutative so the test would otherwise still pass if the order were reversed (!)

File: libraries/postgres/src/Database.js (hunk 2 above)
Comment (djmitche) [reply libraries/postgres/src/Database.js:114]: Yes, good point, although I'd expect those not to come from user input.  But just in case, I can add a somewhat more restrictive regex where we check for the `_in` suffix.

File: libraries/postgres/test/database_test.js (hunk 1 above)
Comment (imbstack) [reply libraries/postgres/test/database_test.js:97]: ah! makes sense

File: libraries/postgres/src/Database.js (hunk 2 above)
Comment (imbstack) [reply libraries/postgres/src/Database.js:117]: ok great. I figured it would be fine for now but who knows what future-us will end up doing with this

**Review by imbstack — APPROVED** [review]
