### PR TITLE
fix(github) Fix artifact fetch due to permission issue

### LINKED ISSUE #5669: Enhance github integration: Include more useful information in check run output
At the moment, when task is finished, github service is sending `output.text` information for each check run, like [here](https://github.com/taskcluster/taskcluster/pull/7057/checks?check_run_id=26643525105)

At the moment it includes:

```
[link to the task]
[link to the logs]

< contents of the public/github/customCheckRunText.md artifact if it exists >

---
< last 250 lines of live.log >
```

Some ideas what could be included as well, in order to provide as much information as possible:

- total task execution time, when started, when finished, how long it took
- always include beginning of the logs which contains worker details, version and environment info
- link to the task group
- exact status information: failed, canceled, exceptions, number of runs, ..
- attach list of artifacts produced by this build (with links)

### PR DESCRIPTION
**Pull request by thakkarujas5**
Fixes #5669 

Fix artifact url generation
Fix artifact fetch due to missing permission issues
Hide headers in checkrun for absent values

### CODE REVIEW

File: services/github/src/handlers/utils.js [hunk 1]
```diff
@@ -232,7 +232,7 @@ export const getTimeDifference = (timestamp1, timestamp2) => {
 };
 
 export const buildUrl = (rootUrl, taskId, runId, artifactName) => {
-  return `${rootUrl}/tasks/${taskId}/runs/${runId}/${artifactName}`;
+  return `${rootUrl}/tasks/${taskId}/runs/${runId}/logs/${artifactName}`;
```
Comment (lotas) [inline services/github/src/handlers/utils.js:235]: `/logs` was probably a special case of artifacts, sorry. We'd likely need to check the name also: https://github.com/taskcluster/taskcluster/blob/main/ui/src/views/Tasks/routes.js#L63-L71

And maybe this only works for the logs.. 
I think we can only link those two logs (log, live log) directly, and all other artifact links should just point to the task page (so url ends with runId) 
Thanks!

**Review by lotas — APPROVED** [review]
Thanks!
