### PR TITLE
[UI] Add deep links for roles and scope views

### LINKED ISSUE #2129: [UI] Deep link views roles, clients, scope views
**Describe the bug**
The `/auth/scopes`, `/auth/roles` views are not deep-linked. In other words, you cannot search for something then share the URL with somebody else without losing the refined search result.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/auth/scopes
2. Search for something in the app bar (e.g., "list") and press enter
3. Search a client/role in the app bar (e.g., "ci-admin") and press enter
3. Look at the new updated list
3. Refresh the page

**Actual behavior**
The old list is showing (before typing "ci-admin").

**Expected behavior**
The new list is showing (after typing "ci-admin").

**Taskcluster version**
23.0.0

### PR DESCRIPTION
**Pull request by ss77995ss**
### Description
* Fixes #2129 
* Use `history.location.search` to store data which we needed

### CODE REVIEW

File: ui/src/views/Roles/ViewRoles/index.jsx [hunk 1]
```diff
@@ -16,10 +17,18 @@ import HelpView from '../../../components/HelpView';
...
 
   handleRoleSearchSubmit = roleSearch => {
+    if (roleSearch !== this.state.roleSearch) {
+      this.props.history.push(
+        roleSearch.length > 0 ? `?${stringify({ roleSearch })}` : '/auth/roles'
+      );
+    }
+
     this.setState({ roleSearch });
   };
```
Comment (helfi92) [inline ui/src/views/Roles/ViewRoles/index.jsx:34]: STR:

1. Navigate to http://localhost:5080/auth/roles?roleSearch=foo

Expected:

Screen Shot 2020-04-15 at 3 00 08 PM

Actual:

Screen Shot 2020-04-15 at 3 00 02 PM


This applies to the the other view as well.

File: ui/src/views/Roles/ViewRoles/index.jsx [hunk 2]
```diff
@@ -16,10 +17,18 @@ import HelpView from '../../../components/HelpView';
...
+    roleSearch: this.props.history.location.search
+      ? parse(this.props.history.location.search.slice(1)).roleSearch
+      : '',
   };
 
   handleRoleSearchSubmit = roleSearch => {
+    if (roleSearch !== this.state.roleSearch) {
+      this.props.history.push(
+        roleSearch.length > 0 ? `?${stringify({ roleSearch })}` : '/auth/roles'
+      );
```
Comment (helfi92) [inline ui/src/views/Roles/ViewRoles/index.jsx:29]: I think you should be able to use (untested)

```jsx
const { location, history } = this.props;
const query = parse(location.search.slice(1));

if (query.roleSearch !== roleSearch) {
  query.roleSearch = roleSearch;

  history.push({
    search: stringify(query, { addQueryPrefix: true }),
  });
}
```

This would make sure that if we decide to add more queryies in the future, they won't be removed when a user submits a search. Let's do the same thing in the other view as well.

Comment (ss77995ss) [reply ui/src/views/Roles/ViewRoles/index.jsx:29]: Looks great! Let me have a try, thanks!

File: ui/src/views/Roles/ViewRoles/index.jsx [hunk 3]
```diff
@@ -16,10 +17,23 @@ import HelpView from '../../../components/HelpView';
 }))
 export default class ViewRoles extends PureComponent {
   state = {
-    roleSearch: '',
+    roleSearch: this.props.history.location.search
+      ? parse(this.props.history.location.search.slice(1)).roleSearch
+      : '',
   };
```
Comment (helfi92) [inline ui/src/views/Roles/ViewRoles/index.jsx:23]: Turns out we don't need to use internal state anymore since all the state is stored in the URL:

```diff
diff --git a/ui/src/views/Roles/ViewRoles/index.jsx b/ui/src/views/Roles/ViewRoles/index.jsx
index d550edaae..e01599f03 100644
--- a/ui/src/views/Roles/ViewRoles/index.jsx
+++ b/ui/src/views/Roles/ViewRoles/index.jsx
@@ -16,25 +16,17 @@ import HelpView from '../../../components/HelpView';
   },
 }))
 export default class ViewRoles extends PureComponent {
-  state = {
-    roleSearch: this.props.history.location.search
-      ? parse(this.props.history.location.search.slice(1)).roleSearch
-      : '',
-  };
-
   handleRoleSearchSubmit = roleSearch => {
     const { location, history } = this.props;
     const query = parse(location.search.slice(1));
 
-    if (query.roleSearch !== roleSearch) {
-      query.roleSearch = roleSearch;
+    if (query.search !== roleSearch) {
+      query.search = roleSearch;
 
       history.push({
         search: stringify(query, { addQueryPrefix: true }),
       });
     }
-
-    this.setState({ roleSearch });
   };
 
   handleCreate = () => {
@@ -42,8 +34,9 @@ export default class ViewRoles extends PureComponent {
   };
 
   render() {
-    const { classes, description } = this.props;
-    const { roleSearch } = this.state;
+    const { classes, description, location } = this.props;
+    const query = parse(location.search.slice(1));
+    const roleSearch = query.search ? query.search : '';
 
     return (
       <Dashboard
```

Let's also do the same thing to the other view :)

Comment (ss77995ss) [reply ui/src/views/Roles/ViewRoles/index.jsx]: Great! Thanks for the advice. I just updated this part. Have a look!

File: ui/src/views/Scopes/ViewScope/index.jsx [hunk 4]
```diff
@@ -63,20 +59,46 @@ export default class ViewScope extends Component {
...
 
   handleTabChange = (event, value) => {
-    this.setState({ currentTabIndex: value });
+    const { location, history } = this.props;
+    const query = parse(location.search.slice(1));
+
+    if (query.currentTabIndex !== value) {
+      const newQuery = {
+        ...query,
+        currentTabValue: value,
```
Comment (helfi92) [inline ui/src/views/Scopes/ViewScope/index.jsx:84]: Let's rename to `tabIndex`. Query values from the URL are "current" already.

File: ui/src/views/Scopes/ViewScope/index.jsx [hunk 5]
```diff
@@ -63,20 +59,46 @@ export default class ViewScope extends Component {
...
   render() {
     const {
       classes,
+      location,
       match: { params },
       data: { loading, error, clients, roles },
     } = this.props;
-    const { searchTerm, currentTabIndex } = this.state;
+    const query = parse(location.search.slice(1));
+    const { searchTerm = '', currentTabIndex = 0 } = query;
```
Comment (helfi92) [inline ui/src/views/Scopes/ViewScope/index.jsx:101]: Noticed a possible regression:

STR:

1. Navigate to http://localhost:5080/auth/scopes/test?searchTerm=reality&currentTabValue=1

Expected: The tab focus is on Clients
Actual: The tab focus is on Roles

Screen Shot 2020-04-22 at 4 08 24 PM

File: ui/src/views/Roles/ViewRoles/index.jsx [hunk 6]
```diff
@@ -15,21 +16,30 @@ import HelpView from '../../../components/HelpView';
...
   handleCreate = () => {
     this.props.history.push('/auth/roles/create');
   };
 
   render() {
-    const { classes, description } = this.props;
-    const { roleSearch } = this.state;
+    const { classes, description, location } = this.props;
+    const query = parse(location.search.slice(1));
+    const { roleSearch = '' } = query;
```
Comment (helfi92) [inline ui/src/views/Roles/ViewRoles/index.jsx:42]: Rename `roleSearch` to `search` for the query name (similar to the diff posted earlier).
