### PR TITLE
[UI] Redirect third-party to login strategy directly when only 1 strategy

### LINKED ISSUE #1529: [UI] Redirect third-party to login strategy directly when only 1 strategy
**Describe the bug**
When a third party site tries to get taskcluster credentials, they first need to redirect their users to our site to login. They navigate their users to `/third-party?...`.

**To Reproduce**
1. The frontend reads configuraiton variables from relative URL `./static/env.js` on page load. This file is written during `yarn start`. Modify `UI_LOGIN_STRATEGY_NAMES` to contain only one strategy (e.g., `"UI_LOGIN_STRATEGY_NAMES": "mozilla-auth0",`) and save the file.
2. Go to http://localhost:5080/third-party?client_id=treeherder-1234&redirect_uri=http%3A%2F%2Flocalhost%3A5000&response_type=code&scope=assume%3Atest+hello&state=21&expires=2000+years while being logged out.

**Actual behavior**

For a third party to login, they need to click the "Sign in" button then click on "Sign in with Auth0"

Screen Shot 2019-10-08 at 9 47 01 AM

Screen Shot 2019-10-08 at 9 54 23 AM

**Expected behavior**
When
1. the user is logged out and
2. the url contains `/third-party` and
3. `window.env.UI_LOGIN_STRATEGY_NAMES` has only one login strategy

then redirect directly to that strategy without having the user click on "Sign in" and then clicking on the strategy to use for login.

**Additional context**
For more information on login strategies, refer to [login strategies](https://github.com/taskcluster/taskcluster/tree/master/ui#login-strategies).

### PR DESCRIPTION
**Pull request by Rolikasi**
Add redirect and logic isOneLoginStrategy
Is behavior is right?
Closes #1529

### CODE REVIEW

File: ui/src/views/ThirdPartyLogin/index.jsx [hunk 1]
```diff
@@ -87,6 +88,10 @@ export default class ThirdPartyLogin extends Component {
   render() {
     const { user, data } = this.props;
     const { formData } = this.state;
+    const isOneLoginStrategy =
+      window.env.UI_LOGIN_STRATEGY_NAMES !== ''
+        ? window.env.UI_LOGIN_STRATEGY_NAMES.split(' ').length === 1
+        : false;
```
Comment (helfi92) [inline ui/src/views/ThirdPartyLogin/index.jsx]: We could probably improve readability with:

```jsx
const isOneLoginStrategy =
  window.env.UI_LOGIN_STRATEGY_NAMES &&
  window.env.UI_LOGIN_STRATEGY_NAMES.split(' ').length === 1;
```

File: ui/src/views/ThirdPartyLogin/index.jsx [hunk 2]
```diff
@@ -102,7 +107,10 @@ export default class ThirdPartyLogin extends Component {
             formData={formData}
           />
         )}
-        {!user && <Homepage />}
+        {!user && isOneLoginStrategy && (
+          <Redirect to={`/login/${window.env.UI_LOGIN_STRATEGY_NAMES}`} />
```
Comment (helfi92) [inline ui/src/views/ThirdPartyLogin/index.jsx]: It should open in a new tab instead of redirecting, similar to the current implementation. Apologies for not making this clear.

https://github.com/taskcluster/taskcluster/blob/31e90eaa058c2d360e144c43a2745bc9bd0de064/ui/src/components/SignInDialog/index.jsx#L96

Comment (Rolikasi) [reply ui/src/views/ThirdPartyLogin/index.jsx]: Is this approach good?
{!user && isOneLoginStrategy && (
          window.open(`/login/${window.env.UI_LOGIN_STRATEGY_NAMES}`))}

Comment (helfi92) [reply ui/src/views/ThirdPartyLogin/index.jsx]: Probably. I think you can do `window.open(..., '_blank');`

File: ui/src/views/ThirdPartyLogin/index.jsx [hunk 3]
```diff
@@ -103,6 +106,9 @@ export default class ThirdPartyLogin extends Component {
           />
         )}
         {!user && <Homepage />}
+        {!user &&
+          isOneLoginStrategy &&
+          window.open(`/login/${window.env.UI_LOGIN_STRATEGY_NAMES}`, '_blank')}
```
Comment (helfi92) [inline ui/src/views/ThirdPartyLogin/index.jsx]: This more or less seems to work. Most of the times, I'm seeing two of these pages pop up. It's probably because the redirect to this page is opening a new one since for a split second, `user` is not defined. We probably need to find a way to not open a new window if this view was rendered after a redirect. Perhaps by reading `window.opener`.

```diff
diff --git a/ui/src/views/ThirdPartyLogin/index.jsx b/ui/src/views/ThirdPartyLogin/index.jsx
index 28ef04474..6a4f8486f 100644
--- a/ui/src/views/ThirdPartyLogin/index.jsx
+++ b/ui/src/views/ThirdPartyLogin/index.jsx
@@ -107,7 +107,7 @@ export default class ThirdPartyLogin extends Component {
         )}
         {!user && <Homepage />}
         {!user &&
-          isOneLoginStrategy &&
+          isOneLoginStrategy && window.opener &&
           window.open(`/login/${window.env.UI_LOGIN_STRATEGY_NAMES}`, '_blank')}
       </Dashboard>
     );
```

Comment (helfi92) [reply ui/src/views/ThirdPartyLogin/index.jsx]: Also, if you can rebase on master, that'd be good :)

Comment (helfi92) [reply ui/src/views/ThirdPartyLogin/index.jsx]: A relevant changelog explaining the change may be useful. https://github.com/taskcluster/taskcluster/blob/master/dev-docs/best-practices/changelog.md

Comment (helfi92) [reply ui/src/views/ThirdPartyLogin/index.jsx]: Ugh, I'm afraid `window.opener` won't always work. Sorry, I should have seen this earlier. The good news is that I think we could rely on session storage. I tested the diff below and it seems to work :)

```diff
diff --git a/ui/src/App/Main.jsx b/ui/src/App/Main.jsx
index c48e48039..802d2a2e7 100644
--- a/ui/src/App/Main.jsx
+++ b/ui/src/App/Main.jsx
@@ -66,6 +66,22 @@ export default class Main extends Component {
       fetchPolicy: 'network-only',
     });
     const thirdPartyLogin = isThirdPartyLogin();
+    const isOneLoginStrategy =
+      window.env.UI_LOGIN_STRATEGY_NAMES &&
+      window.env.UI_LOGIN_STRATEGY_NAMES.split(' ').length === 1;
+    const THIRD_PARTY_DID_AUTO_LOGIN_KEY = 'third-party-did-auto-login';
+
+    if (
+      !user &&
+      thirdPartyLogin &&
+      isOneLoginStrategy &&
+      !sessionStorage.getItem(THIRD_PARTY_DID_AUTO_LOGIN_KEY)
+    ) {
+      sessionStorage.setItem(THIRD_PARTY_DID_AUTO_LOGIN_KEY, 'true');
+      window.open(`/login/${window.env.UI_LOGIN_STRATEGY_NAMES}`);
+
+      return;
+    }
 
     if (
       user &&
@@ -74,12 +90,16 @@ export default class Main extends Component {
       data.isLoggedIn === false
     ) {
       onUnauthorize();
+
+      return;
     }
 
     // Users who were logged in earlier manually will be logged out in order to
     // be able to complete the third party login flow.
     if (user && user.identityProviderId === 'manual' && thirdPartyLogin) {
       onUnauthorize();
+
+      return;
     }
 
     // If a third party tries to login but the user is
diff --git a/ui/src/App/index.jsx b/ui/src/App/index.jsx
index 4951988e4..8024efee6 100644
--- a/ui/src/App/index.jsx
+++ b/ui/src/App/index.jsx
@@ -211,7 +211,11 @@ export default class App extends Component {
             <MuiThemeProvider theme={theme}>
               <FontStager />
               <CssBaseline />
-              <Main key={auth.user} routes={routes} error={error} />
+              <Main
+                key={JSON.stringify(auth.user)}
+                routes={routes}
+                error={error}
+              />
             </MuiThemeProvider>
           </ToggleThemeContext.Provider>
         </AuthContext.Provider>
diff --git a/ui/src/views/ThirdPartyLogin/index.jsx b/ui/src/views/ThirdPartyLogin/index.jsx
index 89f77a378..9d9f2d4fa 100644
--- a/ui/src/views/ThirdPartyLogin/index.jsx
+++ b/ui/src/views/ThirdPartyLogin/index.jsx
@@ -35,7 +35,7 @@ export default class ThirdPartyLogin extends Component {
       location: { search },
     } = props;
     const query = parse(search.slice(1));
-    const scopes = query.scope.split(' ');
+    const scopes = (query.scope || []).split(' ');
     const registeredClientId = query.client_id;
 
     if (
@@ -87,9 +87,6 @@ export default class ThirdPartyLogin extends Component {
   render() {
     const { user, data } = this.props;
     const { formData } = this.state;
-    const isOneLoginStrategy =
-      window.env.UI_LOGIN_STRATEGY_NAMES &&
-      window.env.UI_LOGIN_STRATEGY_NAMES.split(' ').length === 1;
 
     return (
       <Dashboard title="Third Party Login">
@@ -106,10 +103,6 @@ export default class ThirdPartyLogin extends Component {
           />
         )}
         {!user && <Homepage />}
-        {!user &&
-          isOneLoginStrategy &&
-          window.opener &&
-          window.open(`/login/${window.env.UI_LOGIN_STRATEGY_NAMES}`, '_blank')}
       </Dashboard>
     );
   }
```

**Comment by Rolikasi** [comment]
Thank you! You opened my eyes)

File: changelog/issue-1529.md [hunk 4]
```diff
@@ -0,0 +1,4 @@
+level: silent
```
Comment (helfi92) [inline changelog/issue-1529.md]:
```suggestion
level: minor
```

File: changelog/issue-1529.md [hunk 5]
```diff
@@ -0,0 +1,4 @@
...
+reference: issue 1529
+---
+Now if users redirect from third party site to get taskcluster credentials with only one strategy they redirect directly to that strategy without having click on "Sign in" and then clicking on the strategy to use for login
```
Comment (helfi92) [inline changelog/issue-1529.md]:
```suggestion
When a third party site tries to login to the deployment, Taskcluster now attempts to auto login when there is only one login strategy configured. Previously, a user had to click on "Sign In" then click on the login strategy.
```

**Comment by helfi92** [comment]
This will create some conflict for merging the material-ui version update PR but since you're the owner of this change, fixing the conflicts shouldn't be too cumbersome.

**Comment by helfi92** [comment]
@all-contributors please add @Rolikasi for code
