### PR TITLE
[web-server] Replace Promise.all in loaders with try/catch

### LINKED ISSUE #2125: [web-server]  Replace Promise.all in loaders with try/catch
**Describe the bug**
If an error is thrown in Promise.all, the whole thing is rejected. We should gracefully catch errors in graphql loaders.

**Taskcluster version**
23.0.0

**Additional context**
We would need to find all `Promise.all` calls in `src/loaders` and replace them with try catch statement. The change should be similar to https://github.com/taskcluster/taskcluster/pull/1944/files.

### PR DESCRIPTION
**Pull request by MooseJ**
Github Bug/Issue: Fixes #2125

I wasn't sure if _everything_ in the `promise.all`'s should be wrapped with try catches, so I did just to be safe. Let me know what you think!

### CODE REVIEW

File: services/web-server/src/loaders/auth.js [hunk 1]
```diff
@@ -15,22 +15,33 @@ module.exports = (clients, isAuthed, rootUrl, monitor, strategies, req, cfg) =>
           throw unauthorizedError;
```
Comment (MooseJ) [inline services/web-server/src/loaders/auth.js]: I left the above code unwrapped since it seemed like the throw unauthorizedError was intentional and probably be handled by the upstream caller. Also if req.user is undefined for one query it will be undefined for the others, so they would all fail anyways.

File: services/web-server/src/loaders/auth.js [hunk 2]
```diff
@@ -15,22 +15,33 @@ module.exports = (clients, isAuthed, rootUrl, monitor, strategies, req, cfg) =>
...
   const isLoggedIn = new DataLoader(queries =>
     Promise.all(
-      queries.map(() => Boolean(req.user)),
+      queries.map(() => {
+        try {
+          return Boolean(req.user);
+        } catch (err) {
+          return err;
+        }
+      }),
```
Comment (helfi92) [inline services/web-server/src/loaders/auth.js]: No need to wrap this in a try catch statement since I don't think `Boolean(req.user)` will ever throw an error.

File: services/web-server/src/loaders/auth.js (hunk 1 above)
Comment (helfi92) [reply services/web-server/src/loaders/auth.js]: That makes a lot of sense. A comment that says what you just commented here would probably help for posterity :)

File: services/web-server/src/loaders/tasks.js [hunk 3]
```diff
@@ -6,16 +6,26 @@ const Task = require('../entities/Task');
...
+        }
+      }),
+    ),
   );
   const indexedTask = new DataLoader(indexPaths =>
-    Promise.all(indexPaths.map(indexPath => index.findTask(indexPath))),
+    Promise.all(
+      indexPaths.map(indexPath => {
+        try {
+          return index.findTask(indexPath);
```
Comment (helfi92) [inline services/web-server/src/loaders/tasks.js]: Hm, I'm not sure if this will throw since we're not awaiting. Perhaps this can be solved with:

```jsx
try {
  return await index.findTask(indexPath);
} catch (err) {
  return err;
}
```

Comment (MooseJ) [reply services/web-server/src/loaders/tasks.js]: Should some other calls that aren't being awaited be awaited as well. Like the one's in `github.js` and `client.js` for example

Comment (helfi92) [reply services/web-server/src/loaders/tasks.js]: Good catch! Yes, please.

**Comment by helfi92** [comment]
@MooseJ Are you interested in writing tests for some of these services? I'm written some in https://github.com/taskcluster/taskcluster/tree/master/services/web-server/test/graphql and https://github.com/taskcluster/taskcluster/tree/master/services/web-server/test/loaders. Let me know if you're interested in that or whether you're looking for something else.

**Comment by MooseJ** [comment]
@helfi92 Yeah I'd be willing to work on tests! I won't be able to start until Sunday though. The graphql tests should be tied to this issue right? https://github.com/taskcluster/taskcluster/issues/2130

**Comment by helfi92** [comment]
> @helfi92 Yeah I'd be willing to work on tests! I won't be able to start until Sunday though.

Awesome!

> The graphql tests should be tied to this issue right? #2130

Correct :)
