### PR TITLE
[UI] Add search feature in purge caches page

### LINKED ISSUE #2865: [UI] Add search feature in /purge-caches
**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/purge-caches

**Expected behavior**
You should be able to search for a cache

**Actual behavior**
There is no easy way to search for a cache name. You need to click the next page button until you find the cache you are looking for.

Like other views, we should add a functional search box in the upper right. Here's an example: https://community-tc.services.mozilla.com/worker-manager of a search box showing in the UI
The code for that example begins in https://github.com/taskcluster/taskcluster/blob/6200d45870f0f3c05aefcef6a814988378b62106/ui/src/views/WorkerManager/WMViewWorkerPools/index.jsx#L138-L142

**Taskcluster version**
v29.6.0

### PR DESCRIPTION
**Pull request by ajinkabeer**
Fixes #2865

> Expected behaviour
> You should be able to search for a cache
> 
> Actual behaviour
> There is no easy way to search for a cache name. You need to click the next page button until you find the cache you are looking for.

- [x]  Add search feature in `Purge Caches` page.

- [x]  Increase the number of entries per page to 1000.

_Screenshots_

new

new2

### CODE REVIEW

File: ui/src/views/CachePurges/ViewCachePurges/index.jsx [hunk 1]
```diff
@@ -67,12 +72,17 @@ export default class ViewCachePurges extends Component {
...
+    this.setState({ cacheSearch });
+  };
+
   render() {
     const {
       classes,
       description,
       data: { loading, error, cachePurges },
     } = this.props;
+    const { cacheSearch } = this.state;
```
Comment (helfi92) [inline ui/src/views/CachePurges/ViewCachePurges/index.jsx:85]: No need to use state. We can have access to the url directly. See how the hooks view does it for example:

https://github.com/taskcluster/taskcluster/blob/7113cdec74550c14d5f2a188f0bc9a047849386f/ui/src/views/Hooks/ListHooks/index.jsx#L55-L56

File: ui/src/utils/constants.js [hunk 2]
```diff
@@ -31,7 +31,7 @@ export const VIEW_ROLES_PAGE_SIZE = 1000;
 export const VIEW_SECRETS_PAGE_SIZE = 100;
 export const VIEW_DENYLIST_PAGE_SIZE = 20;
 export const VIEW_NAMESPACES_PAGE_SIZE = 20;
-export const VIEW_CACHE_PURGES_PAGE_SIZE = 20;
+export const VIEW_CACHE_PURGES_PAGE_SIZE = 1000;
```
Comment (helfi92) [inline ui/src/utils/constants.js:34]: 👌

File: ui/src/views/CachePurges/ViewCachePurges/index.jsx (hunk 1 above)
Comment (ajinkabeer) [reply ui/src/views/CachePurges/ViewCachePurges/index.jsx]: Oh cool tip, that deep links it too.

File: ui/src/utils/constants.js (hunk 2 above)
Comment (ajinkabeer) [reply ui/src/utils/constants.js:34]: Thanks. Hey @helfi92, any plans on migrating class-based components into functional hook components in the future. Just asking :)

Comment (helfi92) [reply ui/src/utils/constants.js:34]: For existent components, we can keep the current behavior to avoid introducing new bugs but for new components, we can definitely use hook components.

Comment (ajinkabeer) [reply ui/src/utils/constants.js:34]: Fair point @helfi92

File: changelog/issue-2876.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+audience: general
```
Comment (helfi92) [inline changelog/issue-2876.md:1]:
```suggestion
audience: users
```

File: changelog/issue-2876.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
...
+level: patch
+reference: issue 2876
+---
+<!-- replace this text with your changelog entry.  See dev-docs/best-practices/changelog.md for help writing changelog entries. -->
```
Comment (helfi92) [inline changelog/issue-2876.md:5]:
```suggestion
The purge cache UI view now allows filtering a search result by cache name.
```

File: ui/src/components/CachePurgesTable/index.jsx [hunk 5]
```diff
@@ -36,16 +42,21 @@ export default class CachePurgesTable extends Component {
...
+      const filteredCache = searchTerm
+        ? cachePurgesConnection.edges.filter(({ node }) =>
+            node.cacheName.includes(searchTerm)
+          )
+        : cachePurgesConnection;
 
-      if (!sortBy) {
+      if (!searchTerm) {
         return cachePurgesConnection;
       }
```
Comment (helfi92) [inline ui/src/components/CachePurgesTable/index.jsx:55]: I just noticed that table sorting doesn't work anymore. Let's fix that.

Comment (ajinkabeer) [reply ui/src/components/CachePurgesTable/index.jsx]: Yes, I figured it out now :)

File: changelog/issue-2876.md (hunk 4 above)
Comment (ajinkabeer) [reply changelog/issue-2876.md:5]: I missed this. From now on I will remember to add description to changelog. Thanks :)

File: changelog/issue-2876.md (hunk 3 above)
Comment (ajinkabeer) [reply changelog/issue-2876.md:1]: Done!

**Comment by ajinkabeer** [comment]
> Code looks good. I'll test this in a bit to make sure everything works before merging :) Good work!

Thank you so much!
