### PR TITLE
Fix "e.artifacts is null" and improve UI error handling

### LINKED ISSUE #3839: e.artifacts is null
**Describe the bug**
Viewing a task gives "e.artifacts is null"

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/bOh0SMjqT_uOGdJax_ZKkQ

**Taskcluster version**
38.0.1

Traceback suggests `getLivelogArtifactFromRun` is to blame.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #3839

This at least *changes* how #3831 behaves, so perhaps the fix for that issue should be based on this one.

### CODE REVIEW

File: ui/src/components/ErrorPanel/index.jsx [hunk 1]
```diff
@@ -97,25 +97,57 @@ export default class ErrorPanel extends Component {
...
+        }
+      });
+
+      // construct a markdown summary of all of the errors
+      if (errors.length > 1) {
+        message.push('Multiple errors from web-server:');
+
+        errors.forEach(err => {
+          message.push(`* ${err.message}`);
+        });
```
Comment (helfi92) [inline ui/src/components/ErrorPanel/index.jsx:124]: In the past we would only show the first error to avoid having a very massive error panel show up when the user is missing a lot of scopes. Would it still make sense to only show the first error or perhaps put a limit on how many messages we can render from this array (e.g., only show 2/3 messages at most)?

**Review by helfi92 — COMMENTED** [review]
Just one minor concern, otherwise this is awesome!

File: ui/src/components/ErrorPanel/index.jsx (hunk 1 above)
Comment (djmitche) [reply ui/src/components/ErrorPanel/index.jsx:124]: Good point.  I'll limit it to 3 with an "and N additional errors".

**Comment by djmitche** [comment]
I'll merge if that's green when I get back from ☕ but feel free to click merge sooner than that :)

**Review by helfi92 — APPROVED** [review]
