### PR TITLE
[UI] Deep Link search in /secrets

### LINKED ISSUE #2123: [UI] Deep link search in /secrets
**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/secrets/
2. Type "project/" in the search bar located in the app bar and then press enter.
3. Click on any secret
4. Click back

**Expected behavior**
The list of secrets only contains secrets that start with "project/".

**Taskcluster version**
23.0.0

**Additional context**
In order to fix this issue, we would need to use a query parameter (e.g., search). An example would be `https://firefox-ci-tc.services.mozilla.com/secrets?search=project%2F`.

### PR DESCRIPTION
**Pull request by Manish-Giri**
@helfi92 I noticed the intended behavior for `/secrets` already exists in `/hooks`, and can be seen here (as an example) - https://firefox-ci-tc.services.mozilla.com/hooks?search=project-

So I figured it might be worth a try to replicate the functionality already present in `ListHooks/index.jsx`. 

This change uses the `qs` package to parse out the search term from the query string, and pushes it onto `history`. Thus, once you do the following steps -
1. Visit `/secrets` and search for an item, example `project/`
2. Click on a secret
3. Go back

The browser URL now contains the search term you searched for -

Screenshot 2020-04-13 23 34 30

whereas it is currently just `/secrets` after you go back -

Screenshot 2020-04-13 22 08 03

However, the page still lists all the available results at `/secrets`. 

I wasn't quite sure about why this behavior at `/secrets` is different from `/hooks`, so I figured it would be nice to get your thoughts on this, if possible, before I investigate further. I wonder if the `refetch()` in the Submit Handler from [here](https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/Secrets/ViewSecrets/index.jsx#L46-L53) makes any difference. However, the [docs](https://www.apollographql.com/docs/react/data/queries/#refetching) from Apollo GraphQL mention this just refreshes the query results in response to a user action, and as far as I can see, the `filter` still lists the correct search string -

Would be really great if I could some thoughts/tips about the next steps!

Screenshot 2020-04-13 23 33 02

Github Bug/Issue: Fixes #2123

### CODE REVIEW

File: ui/src/views/Secrets/ViewSecrets/index.jsx [hunk 1]
```diff
@@ -36,6 +37,18 @@ export default class ViewSecrets extends Component {
...
+    const searchString = qs.parse(nextProps.location.search, {
+      ignoreQueryPrefix: true,
+    }).search;
+
+    if (prevState.secretSearch !== searchString) {
+      return { secretSearch: searchString };
+    }
+
+    return null;
+  }
```
Comment (helfi92) [inline ui/src/views/Secrets/ViewSecrets/index.jsx:50]: I just created https://github.com/taskcluster/taskcluster/pull/2660/commits/bd9db1a9905a204a816379468d401394e6ef740c to move away from this kind of logic 😅 See how there's a simpler way to do this without relying on internal state.

File: ui/src/views/Secrets/ViewSecrets/index.jsx [hunk 2]
```diff
@@ -51,6 +64,10 @@ export default class ViewSecrets extends Component {
         ? { name: { $regex: escapeStringRegexp(secretSearch), $options: 'i' } }
         : null,
     });
+
+    this.props.history.push(
+      `/secrets${secretSearch ? `?search=${secretSearch}` : ''}`
```
Comment (helfi92) [inline ui/src/views/Secrets/ViewSecrets/index.jsx:69]: Let's encode the search term before pushing it to history similar to how it's done in https://github.com/taskcluster/taskcluster/pull/2660/commits/bd9db1a9905a204a816379468d401394e6ef740c.

Comment (helfi92) [reply ui/src/views/Secrets/ViewSecrets/index.jsx:69]: On a second thought, there's no need to encode if we use the `stringify` function from the `qs` package. https://github.com/taskcluster/taskcluster/blob/978b8dc93e54d5ec34cfbd06cad6c88796f53f5f/ui/src/views/Hooks/ListHooks/index.jsx#L36-L45

**Comment by Manish-Giri** [comment]
@helfi92 Sorry for the delay. I have been trying to explore React Router, especially `history` for a while now, to figure out what the possible cause might be, for the incorrect behavior of the back button after a search, but couldn't come up with a concrete reason.

Essentially, in the latest commit, I made the following changes -
1. Replaced internal state with the search being derived from `window.location.search`, following the approach in your recent commit, as you pointed out.
2. Also updated the PageChangeHandler accordingly, in addition to the Submit Handler, to not rely on `state`.
3. Added a `defaultValue` prop to the `Search` component in the `render()` function (I was testing to see if this made a difference...).

But, even though the search results correctly display the search term, this behavior doesn't persist after pressing the back button (displayed in screenshots below) -

1. Search for `cia/` -

Screenshot 2020-04-26 05 12 34

2. Click on one of the search results and go back -

Screenshot 2020-04-26 05 13 02

**Comment by helfi92** [comment]
@Manish-Giri Let me know when you want me to review :-)

**Comment by Manish-Giri** [comment]
@helfi92 Thank You! I think I understand your suggested changes. I’ll fix this right away and re-submit.

**Comment by helfi92** [comment]
Awesome! Thanks @Manish-Giri :-)

**Comment by Manish-Giri** [comment]
@helfi92 Sorry for the delay, once again :/

The search works perfectly now - only secrets that include the search term that was searched for originally, are now shown, when you click on the searched secret, and go back. Here is a screenshot for search of`project/` -  only secrets with `project/` are now shown when you go back -

Screenshot 2020-05-18 04 49 55

However, while rebasing with the latest `master`, I noticed there was some work done on [this file](https://github.com/taskcluster/taskcluster/pull/2617/files) as part of #2617, which included maintaining a `state` in the `ViewSecrets` component. Since we were trying to eliminate the need for maintaining a state in the component, I removed `state`, while keeping other changes from that PR. 
The only thing I was a bit confused about is this line here - 
https://github.com/taskcluster/taskcluster/blob/278a92188b830699b7a75be0badeb96106f5d490/ui/src/views/Secrets/ViewSecrets/index.jsx#L101

which, I think, attempts to destructure `searchTerm` from `state` and then pass it on as a prop to the `SecretsTable` component -
https://github.com/taskcluster/taskcluster/blob/278a92188b830699b7a75be0badeb96106f5d490/ui/src/views/Secrets/ViewSecrets/index.jsx#L119

However, `state` only contains a `secretSearch` property, as far as I could tell, so not sure what's going on there. I assume this is meant to capture the search term, if so, I simply used the existing search term we already obtained from `qs.parse` and then pass it on as the `searchTerm` prop. 

```
const query = qs.parse(this.props.location.search.slice(1));
const secretSearch = query.search;
```
If that is not the case, I can make changes accordingly. 

Thank You!

**Comment by Manish-Giri** [comment]
@helfi92 I rebased it with the latest `master`. I didn't know if the PR needed a changelog, so I didn't add it in, looks like the missing changelog might be one of the errors. If you think it needs the changelog, please let me know an appropriate changelog message and I'll add it in. Thank You!

**Comment by Manish-Giri** [comment]
@helfi92 Thank You so much for all your help with this PR. Should I now start looking at #2124 (fix search in `/worker-manager`), since the underlying issue is the same?

As a side note, I wonder if it would be possible to include me in the [Taskcluster contributors list on the repo](https://github.com/taskcluster/taskcluster#contributors). Sorry if this is a restricted list, but I figured it wouldn't hurt to ask, it would just mean a lot to me to have been able to contribute to Taskcluster 'officially'!

**Comment by helfi92** [comment]
> @helfi92 Thank You so much for all your help with this PR. Should I now start looking at #2124 (fix search in `/worker-manager`), since the underlying issue is the same?

That would be so awesome. I'll go ahead and assign you to the issue now. Thanks for helping as always!

> 
> As a side note, I wonder if it would be possible to include me in the [Taskcluster contributors list on the repo](https://github.com/taskcluster/taskcluster#contributors). Sorry if this is a restricted list, but I figured it wouldn't hurt to ask, it would just mean a lot to me to have been able to contribute to Taskcluster 'officially'!

Of course! You should definitely be on that list. I'm on it :)

**Comment by helfi92** [comment]
@all-contributors please add @Manish-Giri for code.
