### PR TITLE
fix(ui): Fix graphql filter query for TaskGroup

### LINKED ISSUE #6124: "Malformed query. $or cannot be matched against property." error on TaskGroup view
Appears on tasks like: 
https://firefox-ci-tc.services.mozilla.com/tasks/groups/NDmBiN1xTaKxrGWYAH21rg 
https://firefox-ci-tc.services.mozilla.com/tasks/groups/Os0-T2r_TpyF2M2DOYnwaQ

Sometimes it disappears as new tasks are being loaded, sometimes it stays.

This is possibly coming from this recent renovatebot upgrade:
https://github.com/taskcluster/taskcluster/pull/6102

<details>
<summary>Graphql request:</summary>

```js
{
  "operationName": "TaskGroup",
  "variables": {
    "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
    "taskGroupConnection": {
      "limit": 20
    },
    "taskActionsFilter": {
      "kind": {
        "$in": [
          "task",
          "hook"
        ]
      },
      "context": {
        "$or": [
          {
            "$size": 0
          },
          {
            "$size": 1
          }
        ]
      }
    }
  },
  "query": "query TaskGroup($taskGroupId: ID!, $taskGroupConnection: PageConnection, $filter: JSON, $taskActionsFilter: JSON) {
      taskGroup(
      taskGroupId: $taskGroupId
      connection: $taskGroupConnection
      filter: $filter
    ) {
        pageInfo {
          hasNextPage
        hasPreviousPage
        cursor
        previousCursor
        nextCursor
        __typename
      }
      taskGroup {
          taskGroupId
        schedulerId
        expires
        sealed
        __typename
      }
      edges {
          node {
            taskId
          metadata {
              name
            __typename
          }
          taskGroupId
          status {
              state
            runs {
                runId
              started
              resolved
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    task(taskId: $taskGroupId) {
        taskQueueId
      schedulerId
      taskId
      taskGroupId
      dependencies
      requires
      routes
      priority
      retries
      created
      deadline
      scopes
      payload
      metadata {
          name
        description
        owner
        source
        __typename
      }
      tags
      extra
      __typename
    }
    taskActions(taskGroupId: $taskGroupId, filter: $taskActionsFilter) {
        actions
      variables
      version
      __typename
    }
  }
  "
}
```
</details>

<details>
<summary>Graphql response</summary>

```js
{
  "errors": [
    {
      "message": "Malformed query. $or cannot be matched against property.",
      "locations": [
        {
          "line": 71,
          "column": 3
        }
      ],
      "path": [
        "taskActions"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": {
    "taskGroup": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "cursor": "$$FIRST$$",
        "previousCursor": null,
        "nextCursor": null,
        "__typename": "PageInfo"
      },
      "taskGroup": {
        "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
        "schedulerId": "releng-level-1",
        "expires": "2024-03-21T21:04:40.020Z",
        "sealed": null,
        "__typename": "TaskGroupInfo"
      },
      "edges": [
        {
          "node": {
            "taskId": "fxp2RoP1QNOQA28_L8eBlg",
            "metadata": {
              "name": "tests-frontend-node-14",
              "__typename": "TaskMetadata"
            },
            "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
            "status": {
              "state": "COMPLETED",
              "runs": [
                {
                  "runId": 0,
                  "started": "2023-03-22T20:08:18.092Z",
                  "resolved": "2023-03-22T20:10:17.966Z",
                  "__typename": "TaskRun"
                }
              ],
              "__typename": "TaskStatus"
            },
            "__typename": "Task"
          },
          "__typename": "TasksEdge"
        },
        {
          "node": {
            "taskId": "JqHYy-_sTQSz3GpZMn5bLA",
            "metadata": {
              "name": "build-docker-image-python39",
              "__typename": "TaskMetadata"
            },
            "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
            "status": {
              "state": "FAILED",
              "runs": [
                {
                  "runId": 0,
                  "started": "2023-03-22T20:08:10.501Z",
                  "resolved": "2023-03-22T20:08:36.898Z",
                  "__typename": "TaskRun"
                }
              ],
              "__typename": "TaskStatus"
            },
            "__typename": "Task"
          },
          "__typename": "TasksEdge"
        },
        {
          "node": {
            "taskId": "NDmBiN1xTaKxrGWYAH21rg",
            "metadata": {
              "name": "Decision Task",
              "__typename": "TaskMetadata"
            },
            "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
            "status": {
              "state": "COMPLETED",
              "runs": [
                {
                  "runId": 0,
                  "started": "2023-03-22T20:06:07.173Z",
                  "resolved": "2023-03-22T20:06:27.568Z",
                  "__typename": "TaskRun"
                }
              ],
              "__typename": "TaskStatus"
            },
            "__typename": "Task"
          },
          "__typename": "TasksEdge"
        },
        {
          "node": {
            "taskId": "MEPEuLL_Qlme2TbvsbOoYQ",
            "metadata": {
              "name": "codecov-upload",
              "__typename": "TaskMetadata"
            },
            "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
            "status": {
              "state": "UNSCHEDULED",
              "runs": [],
              "__typename": "TaskStatus"
            },
            "__typename": "Task"
          },
          "__typename": "TasksEdge"
        },
        {
          "node": {
            "taskId": "N1_7mKMOTr-45a26TCIpVw",
            "metadata": {
              "name": "pr-complete",
              "__typename": "TaskMetadata"
            },
            "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
            "status": {
              "state": "UNSCHEDULED",
              "runs": [],
              "__typename": "TaskStatus"
            },
            "__typename": "Task"
          },
          "__typename": "TasksEdge"
        },
        {
          "node": {
            "taskId": "XuAD0JXcSw2Xv10g5s-LSg",
            "metadata": {
              "name": "tests-api-python-39",
              "__typename": "TaskMetadata"
            },
            "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
            "status": {
              "state": "UNSCHEDULED",
              "runs": [],
              "__typename": "TaskStatus"
            },
            "__typename": "Task"
          },
          "__typename": "TasksEdge"
        }
      ],
      "__typename": "TaskGroupConnection"
    },
    "task": {
      "taskQueueId": "releng-1/decision-gcp",
      "schedulerId": "releng-level-1",
      "taskId": "NDmBiN1xTaKxrGWYAH21rg",
      "taskGroupId": "NDmBiN1xTaKxrGWYAH21rg",
      "dependencies": [],
      "requires": "ALL_COMPLETED",
      "routes": [
        "checks"
      ],
      "priority": "LOWEST",
      "retries": 5,
      "created": "2023-03-22T20:04:39.020Z",
      "deadline": "2023-03-23T20:04:39.020Z",
      "scopes": [
        "assume:repo:github.com/mozilla-releng/shipit:pull-request"
      ],
      "payload": {
        "env": {
          "REPOSITORIES": "{\"shipit\":\"Shipit\"}",
          "SHIPIT_HEAD_REF": "poetry",
          "SHIPIT_HEAD_REV": "e61c8ee2ac92e6d8d1340c9424298a4d1309db48",
          "SHIPIT_BASE_REPOSITORY": "https://github.com/mozilla-releng/shipit",
          "SHIPIT_HEAD_REPOSITORY": "https://github.com/bhearsum/shipit",
          "SHIPIT_REPOSITORY_TYPE": "git",
          "SHIPIT_PIP_REQUIREMENTS": "taskcluster/requirements.txt",
          "SHIPIT_PULL_REQUEST_NUMBER": "1304"
        },
        "image": "mozillareleases/taskgraph:decision-97d621201199881db8f9971d65c077419ddbc34412a8c22e21d51be8a31619a9@sha256:fdc474519fe1bf26bcb7fe4947cd53b7ef71bd985659bb476e530330c4b86910",
        "command": [
          "/usr/local/bin/run-task",
          "--shipit-checkout=/builds/worker/checkouts/src",
          "--task-cwd=/builds/worker/checkouts/src",
          "--",
          "bash",
          "-cx",
          "ln -s /builds/worker/artifacts artifacts && ~/.local/bin/taskgraph decision --pushlog-id='0' --pushdate='0' --project='shipit' --message=\"\" --owner='bhearsum@users.noreply.github.com' --level='1' --base-repository=\"$SHIPIT_BASE_REPOSITORY\" --head-repository=\"$SHIPIT_HEAD_REPOSITORY\" --head-ref=\"$SHIPIT_HEAD_REF\" --head-rev=\"$SHIPIT_HEAD_REV\" --repository-type=\"$SHIPIT_REPOSITORY_TYPE\" --tasks-for='github-pull-request' \n"
        ],
        "features": {
          "chainOfTrust": true,
          "taskclusterProxy": true
        },
        "artifacts": {
          "public": {
            "path": "/builds/worker/artifacts",
            "type": "directory",
            "expires": "2024-03-21T20:04:39.020Z"
          },
          "public/docker-contexts": {
            "path": "/builds/worker/checkouts/src/docker-contexts",
            "type": "directory",
            "expires": "2023-03-29T20:04:39.020Z"
          }
        },
        "maxRunTime": 1800
      },
      "metadata": {
        "name": "Decision Task",
        "description": "The task that creates all of the other tasks in the task graph",
        "owner": "bhearsum@users.noreply.github.com",
        "source": "https://github.com/bhearsum/shipit/raw/e61c8ee2ac92e6d8d1340c9424298a4d1309db48/.taskcluster.yml",
        "__typename": "TaskMetadata"
      },
      "tags": {
        "kind": "decision-task"
      },
      "extra": {
        "tasks_for": "github-pull-request"
      },
      "__typename": "Task"
    },
    "taskActions": null
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by lotas**
This error wasn't showing up on community-tc because we don’t use `actions.json` artifact.. but on fxci it is being used, so when it is not empty, graphql loader is trying to filter those actions with broken filter (filter that might be working with old library, but is not with the new one)

Fixes #6124

### CODE REVIEW

File: ui/src/views/Tasks/TaskGroup/index.jsx [hunk 1]
```diff
@@ -96,9 +96,10 @@ const updateTaskGroupIdHistory = id => {
         kind: {
           $in: ACTIONS_JSON_KNOWN_KINDS,
         },
-        context: {
-          $or: [{ $size: 0 }, { $size: 1 }],
-        },
+        $or: [
+          { context: { $size: 0 } },
+          { context: { $size: 1 } }
+        ],
```
Comment (matt-boris) [inline ui/src/views/Tasks/TaskGroup/index.jsx:102]: There's another instance of this on line 524 that likely needs fixed too then

**Review by matt-boris — CHANGES_REQUESTED** [review]
Thanks for finding/fixing so fast Yarik! I think there's one more instance of this filtering that should be updated.

File: ui/src/views/Tasks/TaskGroup/index.jsx (hunk 1 above)
Comment (lotas) [reply ui/src/views/Tasks/TaskGroup/index.jsx:102]: oh! Totally right, thank you.!

Comment (matt-boris) [inline ui/src/views/Tasks/TaskGroup/index.jsx:102]:
```suggestion
        $or: [{ context: { $size: 0 } }, { context: { $size: 1 } }],
```

File: ui/src/views/Tasks/TaskGroup/index.jsx [hunk 2]
```diff
@@ -520,9 +521,10 @@ export default class TaskGroup extends Component {
           kind: {
             $in: ACTIONS_JSON_KNOWN_KINDS,
           },
-          context: {
-            $or: [{ $size: 0 }, { $size: 1 }],
-          },
+          $or: [
+            { context: { $size: 0 } },
+            { context: { $size: 1 } }
+          ],
```
Comment (matt-boris) [inline ui/src/views/Tasks/TaskGroup/index.jsx:527]:
```suggestion
          $or: [{ context: { $size: 0 } }, { context: { $size: 1 } }],
```

**Review by matt-boris — COMMENTED** [review]
To make the linter happy 🙃

File: ui/src/views/Tasks/TaskGroup/index.jsx (hunk 2 above)
Comment (lotas) [reply ui/src/views/Tasks/TaskGroup/index.jsx]: thank you @matt-boris , applied lint :)

**Comment by lotas** [comment]
Verified locally, fix works: 
image

File: ui/src/views/Tasks/TaskGroup/index.jsx (hunk 1 above)
Comment (lotas) [reply ui/src/views/Tasks/TaskGroup/index.jsx]: applied, thanks
