### PR TITLE
fix(w-m): transition aws/gcp workers to stopping on `removeWorker` call

### LINKED ISSUE #7322: AWS/GCP workers never go into stopping state while being terminated
Stopping state was only used for Azure, but this can cause a bit of confusion seeing running workers, even if they're currently being terminated. I think they should transition from running to stopping once `removeWorker` is called, then worker scanner will properly move to stopped once it sees they're fully terminated.

### PR DESCRIPTION
**Pull request by matt-boris**
Fixes #7322.

>Worker Manager: AWS and GCP workers now transition into stopping state on call to `removeWorker`.

### CODE REVIEW

File: services/worker-manager/src/providers/aws.js [hunk 1]
```diff
@@ -383,6 +383,12 @@ export class AwsProvider extends Provider {
   }
 
   async removeWorker({ worker, reason }) {
+    await worker.update(this.db, worker => {
```
Comment (lotas) [inline services/worker-manager/src/providers/aws.js:386]: I'd probably rename this inner variable to avoid shadowing and guessing which value is being updated

Comment (matt-boris) [reply services/worker-manager/src/providers/aws.js]: Good call, thanks. It was a copy/pasta, so I updated the original as well 👍🏻

**Review by lotas — APPROVED** [review]
Thanks!
