### PR TITLE
Fix handling of tasks on which lots of tasks depend

### LINKED ISSUE #3366: pagination by taskId in get_dependent_tasks doesn't work because results aren't sorted
* Reproduce in a test case
* Fix

Follow-on to #3363.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #3366

### CODE REVIEW

**Comment by djmitche** [comment]
r? to @imbstack since he looked at my "math" in #3363 and has at least a little context.

File: db/test/fns/queue_test.js [hunk 1]
```diff
@@ -750,6 +751,131 @@ suite(testing.suiteName(), function() {
...
+          } else if (sat === false) {
+            assert.deepEqual(
+              rows.map(row => row.dependent_task_id).sort(),
+              deps.filter((d, i) => !(i & 1)).sort(),
+              'sat = false');
+          }
+        }
+      });
+
+      helper.dbTest('taskId-bsaed pagination and filtering by satisfied', async function(db) {
```
Comment (helfi92) [inline db/test/fns/queue_test.js:842]: bsaed
