### PR TITLE
[Web server] Tasks Subscriptions Test

### LINKED ISSUE #2130: [web-server] Add graphql tests
**Describe the bug**
Whenever we get new updates from the renovate-bot to bump package versions related to the web-server service, we are [not confident](https://github.com/taskcluster/taskcluster/pull/2067#issuecomment-558659636) 100% that things will still work. We should look into adding some tests to tests graphql queries, mutations, and subscriptions.

### PR DESCRIPTION
**Pull request by MooseJ**
Github Bug/Issue: Fixes #2130

### CODE REVIEW

**Comment by MooseJ** [comment]
So I'm not sure why the checks are failing. 
I took a look at the logs for test:meta https://community-tc.services.mozilla.com/tasks/KSt4kZOaSb-OxXs0S8VAMg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FKSt4kZOaSb-OxXs0S8VAMg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log and I saw an error about missing dependencies for ws? I'm not sure how to fix this.

File: services/web-server/test/graphql/tasks_graphql_test.js [hunk 1]
```diff
@@ -64,4 +68,81 @@ helper.secrets.mockSuite(testing.suiteName(), [], function(mock, skipping) {
...
+
+      return new ApolloClient({ cache, link });
+    };
+
+    test('subscribe works', async function(){
+      // We need to create this subscription client separately so we can close it after our test
+      // Otherwise, our tests will just hang and timeout
+      let subscriptionClient = await createSubscriptionClient();
+      const client = getClient(subscriptionClient);
+      const task = helper.makeTaskDefinition();
```
Comment (djmitche) [inline services/web-server/test/graphql/tasks_graphql_test.js]: It looks like this is unused?  I see that taskGroupId is passed to the subscription on line 131, but that's not actually matched in the response (the response has taskGroupId = "subscribe-task-group-id").

File: services/web-server/test/graphql/tasks_graphql_test.js [hunk 2]
```diff
@@ -64,4 +68,81 @@ helper.secrets.mockSuite(testing.suiteName(), [], function(mock, skipping) {
...
+      };
+
+      helper.SetNextAsyncIterator(asyncIterator);
+
+      let tasksSubscriptionsResult;
+      let taskSubscription = client.subscribe({
+        query: gql`${subscribeTasks}`,
+        variables: {
+          taskGroupId,
+          subscriptions,
```
Comment (djmitche) [inline services/web-server/test/graphql/tasks_graphql_test.js]: So, this could be simplified a bit to 
```suggestion
          taskGroupId: "subscribe-task-group-id",
          subscriptions: ['tasksDefined'],
```

File: services/web-server/test/graphql/tasks_graphql_test.js [hunk 3]
```diff
@@ -64,4 +68,81 @@ helper.secrets.mockSuite(testing.suiteName(), [], function(mock, skipping) {
...
+        },
+      }).subscribe(
+        (value) => tasksSubscriptionsResult = value,
+      );
+
+      //wait for event to be processed
+      await new Promise(resolve => setTimeout(resolve, 10));
```
Comment (djmitche) [inline services/web-server/test/graphql/tasks_graphql_test.js]: Timeouts are really dangerous in tests -- on a busy system, this might end up taking 11ms, in which case the test will fail.  But if you set a longer timeout, then the whole test suite starts to take forever.  A better approach here is to poll, waiting for the result.  We even have [a utility for that](https://github.com/taskcluster/taskcluster/tree/master/libraries/testing#poll)!
```suggestion
      await testing.poll(
        () => assert(tasksSubscriptionResult),
        100, 10);
```
this will try every 10ms for up to a second, then give up.

File: services/web-server/test/helper.js [hunk 4]
```diff
@@ -38,6 +39,32 @@ exports.withEntities = (mock, skipping) => {
...
 
+exports.withPulse = (helper, skipping) => {
+  withPulse({helper, skipping, namespace: 'taskcluster-web-server'});
+};
+
+exports.withMockedEventIterator = () => {
+  let PulseEngineCopy = Object.assign({}, PulseEngine);
+
+  PulseEngineCopy.NextAsyncIterator = null;
+  exports.SetNextAsyncIterator = (asyncIterator) => {
```
Comment (djmitche) [inline services/web-server/test/helper.js]: [nit] this should have a lower-case `s` since it's a function
```suggestion
  exports.setNextAsyncIterator = (asyncIterator) => {
```

File: services/web-server/test/graphql/tasks_graphql_test.js [hunk 5]
```diff
@@ -9,23 +9,27 @@ const testing = require('taskcluster-lib-testing');
 const helper = require('../helper');
 const taskQuery = require('../fixtures/task.graphql');
 const createTaskQuery = require('../fixtures/createTask.graphql');
+const subscribeTasks = require('../fixtures/tasksSubscriptions.graphql');
+const { WebSocketLink } = require('apollo-link-ws');
+const WebSocket = require('ws');
```
Comment (djmitche) [inline services/web-server/test/graphql/tasks_graphql_test.js]: I don't see this package in `package.json`..

**Comment by djmitche** [comment]
Once that is green I'll get this PR merged.  Thanks!  Do you know what you want to work on next?

**Comment by MooseJ** [comment]
@djmitche https://github.com/taskcluster/taskcluster/issues/2293 looks like something I can work on. I can also continue writing graphql tests if more of those are needed, or work on something else that you think might be more important.

**Comment by djmitche** [comment]
#2239 would be great.  And, writing more GraphQL tests would also be great -- the more of those we have, the more confident we are when making changes to web-server.

**Comment by helfi92** [comment]
@MooseJ Did you decide what you wanted to work on next? Happy to help if you had any questions :)

**Comment by MooseJ** [comment]
@helfi92 Yeah sorry, work and life have been keeping me a little busy 😄. I can focus on https://github.com/taskcluster/taskcluster/issues/2293 and slowly continue working on graphql tests along side that.

**Comment by helfi92** [comment]
That works! Thank you so much for your help.

**Comment by helfi92** [comment]
Once you accept the invitation to the org (check your email), I will be able to officially assign the issue to you.
