### PR TITLE
feat(w-m): Worker scanner loop fixes

### LINKED ISSUE #8470: Worker Scanner TypeError: `Cannot read properties of undefined (reading 'westus3')`
>TypeError
Cannot read properties of undefined (reading 'westus3')
TypeError: Cannot read properties of undefined (reading 'westus3') at AzureProvider.checkWorker (file:///app/services/worker-manager/src/providers/azure/index.js:1535:55) at process.processTicksAndRejections (node:internal/process/task_queues:104:5) at async WorkerScanner.scan (file:///app/services/worker-manager/src/worker-scanner.js:75:11) at async Iterate.handler (file:///app/services/worker-manager/src/worker-scanner.js:35:9)
Service
worker-manager
Version
99.0.3

### PR DESCRIPTION
**Pull request by lotas**
- Prevents concurrent scan loops - detect running loop
- Limits Azure call timeout to 1min (p95 calls showed ~35s calls)
- Mark RG as existing early to prevent multiple creation attempts
- `checkWorker` is wrapped with timeout to not take longer than 1min

### CODE REVIEW

File: services/worker-manager/src/providers/azure/index.js [hunk 1]
```diff
@@ -279,6 +279,12 @@ export class AzureProvider extends Provider {
       return;
     }
 
+    // Since there might be multiple launch configs competing to ensure a resource group
+    // it might happen that both try to create it in different regions
+    // so all calls but first would fail.
+    // By marking resource group as existing right away we exit early to avoid multiple creation calls
+    this.resourceGroupCache.set(resourceGroupName, true);
```
Comment (matt-boris) [inline services/worker-manager/src/providers/azure/index.js]: I'm wondering if we'll run into a race condition where the first launch config will set this as ensured, but subsequent launch configs will skip this step and (presumably?) start trying to launch VMs in _this_ RG it depends on?

File: services/worker-manager/src/worker-scanner.js [hunk 2]
```diff
@@ -72,7 +87,11 @@ export class WorkerScanner {
           continue;
         }
         try {
-          await provider.checkWorker({ worker });
+          await withTimeout(
+            provider.checkWorker({ worker }),
+            60_000,
```
Comment (matt-boris) [inline services/worker-manager/src/worker-scanner.js]: Might be nice to just toss a comment right next to this saying how much time this is. Something like:


```suggestion
            60_000, // 1 minute
```

File: services/worker-manager/src/providers/azure/index.js [hunk 3]
```diff
@@ -139,7 +139,7 @@ export class AzureProvider extends Provider {
       apiRateLimits,
       intervalDefault: 100 * 1000, // Intervals are enforced every 100 seconds
       intervalCapDefault: 2000, // The calls we make are all limited 20/sec so 20 * 100 are allowed
-      timeout: 10 * 60 * 1000, // each cloud call should not take longer than 10 minutes
+      timeout: 3 * 60 * 1000, // each cloud call should not take longer than 3 minutes
```
Comment (lotas) [inline services/worker-manager/src/providers/azure/index.js:142]: logs revealed there were few ~150s calls.. so having 3min timeout is very generous :)

File: services/worker-manager/src/worker-scanner.js [hunk 4]
```diff
@@ -72,7 +87,11 @@ export class WorkerScanner {
           continue;
         }
         try {
-          await provider.checkWorker({ worker });
+          await withTimeout(
+            provider.checkWorker({ worker }),
```
Comment (lotas) [inline services/worker-manager/src/worker-scanner.js:91]: note, this doesn't cancel the actual checkWorker call, just limits the time we wait for 1min, before we go onto the next worker. Running checkWorker might come back and finish later

File: changelog/fix-azure-undefined-issue.md [hunk 5]
```diff
@@ -0,0 +1,4 @@
+audience: deployers
+level: patch
```
Comment (matt-boris) [inline changelog/fix-azure-undefined-issue.md:2]:
```suggestion
level: patch
reference: issue 8470
```

File: services/worker-manager/src/providers/azure/index.js [hunk 6]
```diff
@@ -267,31 +267,46 @@ export class AzureProvider extends Provider {
   }
 
   /**
-   * Ensure that a resource group exists, creating it if necessary
-   * Uses in-memory cache to avoid redundant API calls
+   * Ensure that a resource group exists, creating it if necessary.
+   * Concurrent callers for the same resource group coalesce behind a single
+   * in-flight promise so only one check/create cycle runs at a time.
+   * On failure the cache entry is evicted so the next attempt retries.
```
Comment (matt-boris) [inline services/worker-manager/src/providers/azure/index.js:273]: Perfect 👍🏻

**Review by matt-boris — COMMENTED** [review]
Changes LGTM, thank you! Just one quick request to put the issue number in the changelog pls :)

**Review by matt-boris — APPROVED** [review]
Ty!
