### PR TITLE
Workers: create a LinkArtifact from live.log to live_backing.log

### LINKED ISSUE #4050: The live log from generic-worker is not viewable after the task ends without assume:anonymous
**Describe the bug**
After a generic-worker task completes on a Taskcluster instance with an empty anonymous role, the live log link no longer works, instead returning 403.

**To Reproduce**

1. Remove all scopes from the anonymous role.
2. Run a task with generic-worker.
3. Wait for the task to complete.
4. Try to view the live log.
5. See error

**Expected behavior**
The live log link should redirect to `public/live_backing.log` after task completion.

**Taskcluster version**
v39.0.0

**Platform (please complete the following information):**

 - OS: [e.g. windows]
 - Browser if applicable [e.g. firefox, safari]
 - Version if applicable [e.g. 57]

**Additional context**
The UI redirects to:
- https://taskcluster.my.org/api/queue/v1/task/Kko3Y4iMSump_cB7SLdDgA/runs/0/artifacts/public%2Flogs%2Flive.log?bewit=BEWIT
- https://taskcluster.my.org/api/queue/v1/task/Kko3Y4iMSump_cB7SLdDgA/runs/0/artifacts/public%2Flogs%2Flive_backing.log

The second redirect has no credentials (no headers are passed to redirects and there is no bewit), so unless `queue:get-artifact:public/live_backing.log` is fulfilled, the redirect fails.

Example error payload from navigating to the artefact path in the browser:
````
{
  "code": "InsufficientScopes",
  "message": "This request requires Taskcluster credentials that satisfy the following scope expression:\n\n```\nqueue:get-artifact:public/logs/live_backing.log\n```\n\n---\n\n* method:     getArtifact\n* errorCode:  InsufficientScopes\n* statusCode: 403\n* time:       2020-12-07T14:09:32.923Z",
  "requestInfo": {
    "method": "getArtifact",
    "params": {
      "0": "public/logs/live_backing.log",
      "taskId": "Kko3Y4iMSump_cB7SLdDgA",
      "runId": "0",
      "name": "public/logs/live_backing.log"
    },
    "payload": {},
    "time": "2020-12-07T14:09:32.923Z"
  }
}
````

I'm not sure what the best way to solve this is, since the redirect artefact is designed to be flexible. Possible blunt solutions could be along the lines of:
- Allow claimed task credentials to be able to sign URLs that expire when the task does, then store the signed URL in the redirect.
- If the next URL is an artefact URL in the same taskcluster instance, sign the target before redirecting. (ick)

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #4050

### CODE REVIEW

**Comment by djmitche** [comment]
Docker-worker's CI runs against the production instance, so we'll need to wait for [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1685579) before we can test this.

**Comment by djmitche** [comment]
g-w is passing, so I'm just waiting on the 40.0.0 deploy to finish this up.

**Comment by djmitche** [comment]
ok, 40.0.3's running on community, so I've rebased this.  I'll put it up for review if it's green.

**Comment by djmitche** [comment]
Hah, but it requires #4247, which isn't yet released.

**Comment by djmitche** [comment]
@petemoore I misspoke in the meeting yesterday -- this is passing for generic-worker because its tests run against local fakes which have been updated to support `link` artifacts.  Just FYI :)

**Comment by djmitche** [comment]
Waiting on v41

**Comment by djmitche** [comment]
I just pushed a change to add contentType to the link artifacts, which will require #4419 be deployed, so back to draft status..

**Comment by djmitche** [comment]
docker-worker passed! :D

(aside: github now completes `:D` to `:daggers:` which is not exactly what I had in mind)

File: workers/generic-worker/mocktc/queue.go [hunk 1]
```diff
@@ -352,6 +388,13 @@ func (queue *Queue) ListArtifacts(taskId, runId, continuationToken, limit string
 				Name:        name,
 				StorageType: A.StorageType,
 			}
+		case *tcqueue.LinkArtifactRequest:
+			a = tcqueue.Artifact{
+				ContentType: "text/plain", // unused
```
Comment (ricky26) [inline workers/generic-worker/mocktc/queue.go:393]: I'm not sure this comment is correct. Didn't you just add this field because it was needed? :stuck_out_tongue:

Comment (djmitche) [reply workers/generic-worker/mocktc/queue.go:393]: That might have been some copy-🍝!

File: workers/docker-worker/test/integration/container_startup_test.js [hunk 2]
```diff
@@ -26,14 +26,14 @@ helper.secrets.mockSuite(suiteName(), ['docker', 'ci-creds'], function(mock, ski
...
         image: 'taskcluster/test-ubuntu',
         command: [
-          'echo "Hello"',
+          '/usr/bin/no-such-command',
         ],
         maxRunTime: 30,
       },
     });
 
-    assert.equal(result.run.state, 'failed', 'task should be successful');
```
Comment (imbstack) [inline workers/docker-worker/test/integration/container_startup_test.js:35]: huh weird. copy paste maybe?

**Review by imbstack — APPROVED** [review]
assuming the test failures are fixable and/or transient

File: workers/docker-worker/test/integration/container_startup_test.js (hunk 2 above)
Comment (djmitche) [reply workers/docker-worker/test/integration/container_startup_test.js:35]: Yeah -- between that and the clever selection of `/usr/bin/echo "hello"` as the not-found command, this one took a _long_ time to figure out..

**Comment by djmitche** [comment]
I'll check back tomorrow and see if the rebase fixed it.  I had missed a `/v40` -. `/v41` change in the go code.

**Comment by djmitche** [comment]
All Green!
