### PR TITLE
Retry auth failures in smoketests

### LINKED ISSUE #3224: smoketests sometimes fail with role-related issue
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal: (while executing task Create role and expand smoketest (--target roles))

[
  'assume:project:taskcluster:smoketest:cTTAcdksS6qEBLcszMA_4w:abc'
]

should loosely deep-equal

[
  'assume:project:taskcluster:smoketest:cTTAcdksS6qEBLcszMA_4w:abc',
  'project:taskcluster:smoketest:abc/*'
]
    at Object.run (/home/dustin/p/taskcluster/infrastructure/tooling/src/smoketest/checks/role.js:43:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async TaskGraph._runNode (/home/dustin/p/taskcluster/node_modules/console-taskgraph/src/taskgraph.js:184:18) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Array],
  expected: [Array],
  operator: 'deepEqual'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This happened at v32.0.0 and v33.0.0, and it's intermittent.  That check adds the role `project:taskcluster:smoketest:cTTAcdksS6qEBLcszMA_4w:abc` and then immediately expands it, so perhaps this is an issue of a delay in updating the resolvers.

### PR DESCRIPTION
**Pull request by djmitche**
As the comments in the diff indicate, auth doesn't guarantee you can use a role or client immediately on changing it -- there's a small delay while all the web processes get notified via pulse and update their resolvers.  So, retry enough to last that out.

Github Bug/Issue: Fixes #3224

### CODE REVIEW

**Comment by djmitche** [comment]
(oh, and the first commit is there because I got mixed up which deployment I was smoketesting, and this was an easy way to tell)

File: infrastructure/tooling/src/smoketest/checks/ping.js [hunk 1]
```diff
@@ -9,15 +9,31 @@ exports.scopeExpression = {AllOf: []};
...
-  title: `Ping health endpoint for web-server`,
+  title: `Fetch version endpoint for deployment`,
   requires: [],
   provides: [
-    `ping-web-server`,
+    `deployment-version`,
   ],
   run: async (requirements, utils) => {
-    if (process.env.TASKCLUSTER_ROOT_URL === 'https://taskcluster.net') {
-      return utils.skip({reason: 'Not supported on legacy deployment'});
```
Comment (imbstack) [inline infrastructure/tooling/src/smoketest/checks/ping.js:19]: no legacy, no problem!
