### PR TITLE
Fix `claimWork` returning `500`

### LINKED ISSUE #6634: requestClaim() called after destroy()
From GCP logs:
```
 Service    queue 
Version     56.0.3 
```

Stacktrace: 
```
 AssertionError [ERR_ASSERTION]: requestClaim() called after destroy()
    at HintPoller.requestClaim (/app/services/queue/src/hintpoller.js:35:5)
    at WorkClaimer.claim (/app/services/queue/src/workclaimer.js:65:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

### PR DESCRIPTION
**Pull request by lotas**
In some rare conditions, `queue.claimWork` was throwing `500` errors.

This happened because of the changes introduced in recent [queue internals refactoring](https://github.com/taskcluster/taskcluster/commit/3cdec1d6a1c92201cecc5da244f21f05ea67d357#diff-07d1f6e8072664349e5c609273873df2ca0904b88f917517eec8ba91e4ec6a26 )

Adding tests for `HintPoller` and `WorkerClaimer` and making sure destroyed hint poller doesn't interfere with other calls

Fixes #6634

### CODE REVIEW

File: services/queue/src/workclaimer.js [hunk 1]
```diff
@@ -53,17 +53,17 @@ class WorkClaimer extends events.EventEmitter {
...
-
-    const hintPoller = this.getHintPoller(taskQueueId);
+    let hintPoller;
 
     aborted.then(() => done = true);
     // As soon as we have claims we return so work can get started.
     // We don't try to claim up to the count, that could take time and we risk
     // dropping the claims in case of server crash.
     while (claims.length === 0 && !done) {
+      hintPoller = this.getHintPoller(taskQueueId);
```
Comment (lotas) [inline services/queue/src/workclaimer.js:63]: placing it back where it was before to allow new poller to be created when existing gets destroyed inside the queue..

although I'm not able to reproduce it in the tests :-/

**Review by matt-boris — APPROVED** [review]
👍🏻
