### PR TITLE
Bugfix/fix missing curl image

### LINKED ISSUE #4902: docker-worker tests failing
The docker-worker tests began failing a few days ago.  Check pushes to main to see the failures in action.

### PR DESCRIPTION
**Pull request by cerkiewny**
Github Bug/Issue: Fixes #4902

### CODE REVIEW

File: workers/docker-worker/test/integration/docker_manifest_test.js [hunk 1]
```diff
@@ -28,18 +28,18 @@ helper.secrets.mockSuite(suiteName(), ['docker', 'ci-creds'], function(mock, ski
...
     let task1 = await worker.postToQueue({
       payload: {
-        image: 'tutum/curl',
+        image: 'curlimages/curl',
         artifacts: {
           'public/image.tar.zst': {
             type: 'file',
             expires: expires(),
-            path: '/image.tar.zst',
+            path: '/tmp/image.tar.zst',
```
Comment (jwhitlock) [inline workers/docker-worker/test/integration/docker_manifest_test.js:36]: Nice solution!

**Review by jwhitlock — APPROVED** [review]
Thanks @cerkiewny!

File: workers/docker-worker/test/integration/docker_manifest_test.js (hunk 1 above)
Comment (cerkiewny) [reply workers/docker-worker/test/integration/docker_manifest_test.js:36]: thanks!
