### PR TITLE
fix(generic-worker): avoid reclaim creds deadlock

### LINKED ISSUE #8289: [generic worker] credential refresh blocked by `queueMux` during artifact uploads
## Summary

The background goroutine that refreshes task credentials via `ReclaimTask` can be blocked from updating `task.Queue` when many artifacts are being uploaded concurrently. This causes credentials to expire, resulting in 401 errors and worker panics during artifact uploads.

## Root Cause

`task.queueMux` (a `sync.RWMutex`) is held as an RLock for the entire duration of HTTP calls like `CreateArtifact`, including httpbackoff retries (up to 15 minutes). When the reclaim goroutine obtains fresh credentials, it needs a write lock on `queueMux` to swap in the new `task.Queue` client. That write lock is blocked until all in-flight `CreateArtifact` RLocks are released.

Under high artifact load:
1. Multiple upload goroutines hold `queueMux.RLock()` during `CreateArtifact` calls
2. If the queue is under load, httpbackoff retries extend the time these RLocks are held
3. The reclaim goroutine successfully calls `ReclaimTask` and gets new credentials, but blocks on `queueMux.Lock()` waiting for upload goroutines to finish
4. Upload goroutines continue using old credentials until they expire
5. Expired credentials cause 401 (`ext.certificate.expiry < now`), which panics the worker

Additionally, `FinishArtifact` and `DownloadArtifactToFile` read `task.Queue` without any lock at all, which is a data race with the reclaim goroutine's write.

## Related

- #8023 — original issue about micro-DDoS from 100k+ artifact uploads
- #8032 — limited concurrent uploads to 100
- #8167 — reduced limit to 10

Those PRs reduced the likelihood of this occurring by limiting concurrency, but didn't fix the underlying locking issue.

### PR DESCRIPTION
**Pull request by matt-boris**
Fixes #8289.

>Generic Worker: fixes credential expiration during high-volume artifact uploads by narrowing the scope of the queue client lock so that credential refresh is no longer blocked by in-flight HTTP calls.

### CODE REVIEW

File: workers/generic-worker/mounts_feature.go [hunk 1]
```diff
@@ -887,7 +887,10 @@ func (ac *ArtifactContent) Download(taskMount *TaskMount) (file string, sha256 s
 	taskMount.Infof("Downloading %v to %v", ac, file)
 
 	var runID int64 = -1 // use the latest run
-	_, contentLength, err := taskMount.task.Queue.DownloadArtifactToFile(ac.TaskID, runID, ac.Artifact, file)
```
Comment (matt-boris) [inline workers/generic-worker/mounts_feature.go:890]: Was previously a data race with the reclaim goroutine that writes `taskMount.task.Queue`.

File: workers/generic-worker/artifacts.go [hunk 2]
```diff
@@ -147,7 +148,7 @@ func (task *TaskRun) uploadArtifact(artifact artifacts.TaskArtifact) *CommandExe
 		return ResourceUnavailable(e)
 	}
 
-	e = artifact.FinishArtifact(resp, task.Queue, task.TaskID, strconv.Itoa(int(task.RunID)), artifact.Base().Name)
```
Comment (matt-boris) [inline workers/generic-worker/artifacts.go:150]: Was previously a data race with the reclaim goroutine that writes `task.Queue`.

File: workers/generic-worker/artifacts.go [hunk 3]
```diff
@@ -84,13 +84,14 @@ func (task *TaskRun) uploadArtifact(artifact artifacts.TaskArtifact) *CommandExe
 	}
 	par := tcqueue.PostArtifactRequest(json.RawMessage(payload))
 	task.queueMux.RLock()
-	parsp, err := task.Queue.CreateArtifact(
+	queue := task.Queue
```
Comment (lotas) [inline workers/generic-worker/artifacts.go:87]: is there any benefit of introducing this variable?

Comment (matt-boris) [reply workers/generic-worker/artifacts.go:87]: Yes! I'm quickly grabbing the reference to the queue client while holding the lock, then immediately releasing the lock right afterwards. As opposed to holding the lock throughout the entire API call.
