### PR TITLE
feat(ui): Fixes role/clients filtering in the UI

### LINKED ISSUE #6820: scopes UI doesn't filter correctly
Eg:
image

Which is filtering on `project:releng:ship-it:server:production` which is definitely not granted to the `anonymous` role.

### PR DESCRIPTION
**Pull request by lotas**
Fixes roles and clients view, which were not filtered properly:

image
image
image

Fixes #6820

### CODE REVIEW

File: ui/src/components/ClientScopesTable/index.jsx [hunk 1]
```diff
@@ -56,60 +63,55 @@ export default class ClientScopesTable extends Component {
   clients = null;
 
   createSortedClientsConnection = memoize(
-    (clientsConnection, selectedScope) => {
-      const extractClients = pipe(
-        filter(
-          pipe(
-            path(['node', 'expandedScopes']),
-            filter(pipe(toLower, includes(selectedScope), length))
```
Comment (lotas) [inline ui/src/components/ClientScopesTable/index.jsx:64]: Problem was that those nested filter-pipes were not filtering properly.
I tried to figure out for a while how to debug ramda currying pipelines and decided that modern javascript provides all the tools to achieve same results in a more friendly way. 🤷 

I think we can also get rid of it at some point maybe

**Review by matt-boris — APPROVED** [review]
Nice, thanks Yarik 👍🏻
