### PR TITLE
Record table structure in db/tables.yml

### LINKED ISSUE #2541: summarize table columns automatically in db docs
This will work a lot like `access.yml`: a file containing the expected DB configuration (with comments and descriptions) that is compared at test time with the actual DB structure, failing if they do not match.

### PR DESCRIPTION
**Pull request by djmitche**
Github Bug/Issue: Fixes #2541

As an added benefit, this adds a check for any stray timezone-less timestamps.  We can easily add additional assertions about the schema later.

### CODE REVIEW

File: libraries/postgres/src/Relations.js [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+   * Load relations from a file
+   */
+  static fromYamlFileContent(content, filename) {
+    Relations._check(content, filename);
+    const relations = new Relations(content);
+    return relations;
+  }
+
+  /**
+   * Load relatoins from a serialized representation
```
Comment (helfi92) [inline libraries/postgres/src/Relations.js]: `s/relatoins/relations/`

File: libraries/postgres/src/Relations.js [hunk 2]
```diff
@@ -0,0 +1,53 @@
+const {isPlainObject} = require('lodash');
+const assert = require('assert').strict;
+
+class Relations {
```
Comment (helfi92) [inline libraries/postgres/src/Relations.js]: What are relations? A comment here perhaps would help.

Comment (djmitche) [reply libraries/postgres/src/Relations.js]: Will do -- I'm expecting that this will be useful for a `views.yml` too, someday, and "relation" is just a general term for anything with rows and columns, such as tables or views.  I'll add a comment.

**Comment by djmitche** [comment]
I have somehow deeply ingrained the idea that DB changes don't need a changelog, from time working on the development branch.  I'll add one and merge.
