### PR TITLE
Tracking more metrics 

### LINKED ISSUE #7942: Track more metrics with prometheus
Initial implementation covered most important parts, but there's still some other we can cover to track:

- http calls and response statuses
- auth failures
- websocket connections
- queue failed tasks resolutions (claim expired, deadline, etc) https://github.com/taskcluster/taskcluster/blob/a41bfd5d98081cf387e0925e4111882199bd711a/services/queue/src/api.js#L1676

### PR DESCRIPTION
**Pull request by lotas**
1. Collecting api calls metrics
    Renamed `path`->`name` because urls can get quite big, and come with greater variety. This explodes tracked buckets for each. Keeping it down to the api method name avoids having too many entries, plus it is probably safer not to store req.path as is to avoid unexpected injections of malicious stuff
2. enabling metrics exposing for all service that serve api endpoints 
3. auth server logs success/failure counts for auth attempts

Fixes #7942

### CODE REVIEW

File: libraries/monitor/src/builtins.js [hunk 1]
```diff
@@ -166,9 +166,9 @@ MonitorManager.registerMetric('httpRequestsTotal', {
   description: 'Total number of HTTP requests',
   labels: {
     method: 'HTTP method',
-    path: 'HTTP path',
+    name: 'API method name',
```
Comment (lotas) [inline libraries/monitor/src/builtins.js:169]: those metrics wasn't exposed before, so change of label name is not really breaking anything

File: libraries/monitor/src/builtins.js [hunk 2]
```diff
@@ -179,9 +179,9 @@ MonitorManager.registerMetric('httpRequestDurationSeconds', {
   description: 'HTTP request duration in seconds',
   labels: {
     method: 'HTTP method',
-    path: 'HTTP path',
+    name: 'API method name',
     status: 'Response status code',
-    service: 'Serice name',
+    service: 'Service name',
```
Comment (matt-boris) [inline libraries/monitor/src/builtins.js:184]: 🦅👁️

File: services/hooks/src/main.js [hunk 3]
```diff
@@ -100,19 +100,24 @@ const load = loader({
   },
 
   api: {
-    requires: ['cfg', 'db', 'schemaset', 'taskcreator', 'monitor', 'publisher', 'pulseClient'],
-    setup: ({ cfg, db, schemaset, taskcreator, monitor, publisher, pulseClient }) => builder.build({
```
Comment (matt-boris) [inline services/hooks/src/main.js:104]: I noticed `pulseClient` was removed here, is that intentional?

**Review by matt-boris — COMMENTED** [review]
Changes look good to me. Left one question.

File: services/hooks/src/main.js (hunk 3 above)
Comment (lotas) [reply services/hooks/src/main.js:104]: yes, typescript complained it was never used - below not passed to builder, and I checked api.js - it wasn't used there as well

**Review by matt-boris — APPROVED** [review]
