### PR TITLE
Fixed highlight.js issue #4947

### LINKED ISSUE #4947: Deprecated usage of highlight.js 10.7.0
**Describe the bug**

When viewing a task in the UI, this message is displayed in the console:

```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```
The message is generated from ``Tasks.TaskGroup.cd2cd260.js:11:71365``.

**To Reproduce**

1. Open the developer tools, Console
2. Go to https://community-tc.services.mozilla.com/tasks
3. Click to view a task

**Expected behavior**

No deprecation message.

**Taskcluster version**

* Present in 44.1.0 on Community-TC
* Present in 43.2.0 on Firefox-ci

**Additional context**

The linked issue https://github.com/highlightjs/highlight.js/issues/2277 has a working example of changing the call to `highlight`.

### PR DESCRIPTION
**Pull request by Tanmay000009**
Github Bug/Issue: Fixes #4947

### CODE REVIEW

**Comment by Tanmay000009** [comment]
Sorry, have added 2 changelogs by mistake! Please consider the later one

**Comment by Tanmay000009** [comment]
Added correct changelog, and removed two extra changelogs made by me.

File: ui/src/components/Code/index.jsx [hunk 1]
```diff
@@ -35,7 +35,10 @@ export default class Code extends Component {
 
   render() {
     const { children, language, className, ...props } = this.props;
-    const code = highlight(language, children, true).value;
+    const code = highlight(children, {
+      language,
```
Comment (jwhitlock) [inline ui/src/components/Code/index.jsx:39]: Today I learned about ECMAScript 2015's object property shorthand.

File: ui/src/components/Code/index.jsx [hunk 2]
```diff
@@ -35,7 +35,10 @@ export default class Code extends Component {
...
+      ignoreIllegals: true,
+    });
```
Comment (jwhitlock) [inline ui/src/components/Code/index.jsx:41]: When I expand `Payload` on a [task](http://localhost:5080/tasks/a6Baio9sRHyEtLArH07GfQ), it displays `[object Object]` instead of the task definition with syntax highlighting. This should fix it:

```suggestion
    }).value;
```

**Review by jwhitlock — CHANGES_REQUESTED** [review]
Thanks @Tanmay000009! One change (adding `.value`) is required.

In the future, you'll want to make change on a new branch rather than the `main` branch. This will make it easier to keep your fork's `main` branch up-to-date with Taskcluster's `main` branch. It is OK to keep it on `main` for this PR though, it is very close to merging.

File: ui/src/components/Code/index.jsx (hunk 1 above)
Comment (Tanmay000009) [reply ui/src/components/Code/index.jsx:39]: Same,  for me aswell

File: ui/src/components/Code/index.jsx (hunk 2 above)
Comment (Tanmay000009) [reply ui/src/components/Code/index.jsx:41]: Thank you for correcting it.

**Comment by Tanmay000009** [comment]
> Thanks @Tanmay000009! One change (adding `.value`) is required.
> 
> In the future, you'll want to make change on a new branch rather than the `main` branch. This will make it easier to keep your fork's `main` branch up-to-date with Taskcluster's `main` branch. It is OK to keep it on `main` for this PR though, it is very close to merging.

Got your point, will surely keep it in my mind. Thank you!!

**Review by jwhitlock — APPROVED** [review]
Perfect, thanks @Tanmay000009!
